// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/notifications/types.go
//
// Generated by this command:
//
//	mockgen -source=./internal/notifications/types.go -destination=./internal/notifications/mock_service.go -package=notifications Service
//

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	approvals "github.com/freel/backend/internal/approvals"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Acknowledge mocks base method.
func (m *MockService) Acknowledge(ctx context.Context, orgID, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acknowledge", ctx, orgID, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Acknowledge indicates an expected call of Acknowledge.
func (mr *MockServiceMockRecorder) Acknowledge(ctx, orgID, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acknowledge", reflect.TypeOf((*MockService)(nil).Acknowledge), ctx, orgID, id, userID)
}

// AnalyzeWithAI mocks base method.
func (m *MockService) AnalyzeWithAI(ctx context.Context, orgID, id int64) (*NotificationAnalysisResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeWithAI", ctx, orgID, id)
	ret0, _ := ret[0].(*NotificationAnalysisResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeWithAI indicates an expected call of AnalyzeWithAI.
func (mr *MockServiceMockRecorder) AnalyzeWithAI(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeWithAI", reflect.TypeOf((*MockService)(nil).AnalyzeWithAI), ctx, orgID, id)
}

// Dismiss mocks base method.
func (m *MockService) Dismiss(ctx context.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dismiss", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dismiss indicates an expected call of Dismiss.
func (mr *MockServiceMockRecorder) Dismiss(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dismiss", reflect.TypeOf((*MockService)(nil).Dismiss), ctx, orgID, id)
}

// EscalateWithAI mocks base method.
func (m *MockService) EscalateWithAI(ctx context.Context, orgID, id, userID int64, reason string) (*EscalationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EscalateWithAI", ctx, orgID, id, userID, reason)
	ret0, _ := ret[0].(*EscalationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EscalateWithAI indicates an expected call of EscalateWithAI.
func (mr *MockServiceMockRecorder) EscalateWithAI(ctx, orgID, id, userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EscalateWithAI", reflect.TypeOf((*MockService)(nil).EscalateWithAI), ctx, orgID, id, userID, reason)
}

// EvaluateNotifications mocks base method.
func (m *MockService) EvaluateNotifications(ctx context.Context, orgID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateNotifications", ctx, orgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvaluateNotifications indicates an expected call of EvaluateNotifications.
func (mr *MockServiceMockRecorder) EvaluateNotifications(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateNotifications", reflect.TypeOf((*MockService)(nil).EvaluateNotifications), ctx, orgID)
}

// GenerateDraftWithAI mocks base method.
func (m *MockService) GenerateDraftWithAI(ctx context.Context, orgID, id int64, draftType string) (*EscalationDraftResponseDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDraftWithAI", ctx, orgID, id, draftType)
	ret0, _ := ret[0].(*EscalationDraftResponseDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDraftWithAI indicates an expected call of GenerateDraftWithAI.
func (mr *MockServiceMockRecorder) GenerateDraftWithAI(ctx, orgID, id, draftType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDraftWithAI", reflect.TypeOf((*MockService)(nil).GenerateDraftWithAI), ctx, orgID, id, draftType)
}

// GetNotification mocks base method.
func (m *MockService) GetNotification(ctx context.Context, orgID, id int64) (*Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", ctx, orgID, id)
	ret0, _ := ret[0].(*Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockServiceMockRecorder) GetNotification(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockService)(nil).GetNotification), ctx, orgID, id)
}

// GetPreferences mocks base method.
func (m *MockService) GetPreferences(ctx context.Context, orgID, userID int64) (*UserNotificationPreferences, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferences", ctx, orgID, userID)
	ret0, _ := ret[0].(*UserNotificationPreferences)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferences indicates an expected call of GetPreferences.
func (mr *MockServiceMockRecorder) GetPreferences(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferences", reflect.TypeOf((*MockService)(nil).GetPreferences), ctx, orgID, userID)
}

// GetStats mocks base method.
func (m *MockService) GetStats(ctx context.Context, orgID, userID int64, role string) (*NotificationStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, orgID, userID, role)
	ret0, _ := ret[0].(*NotificationStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockServiceMockRecorder) GetStats(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockService)(nil).GetStats), ctx, orgID, userID, role)
}

// GetUnreadCount mocks base method.
func (m *MockService) GetUnreadCount(ctx context.Context, orgID, userID int64, role string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCount", ctx, orgID, userID, role)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCount indicates an expected call of GetUnreadCount.
func (mr *MockServiceMockRecorder) GetUnreadCount(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCount", reflect.TypeOf((*MockService)(nil).GetUnreadCount), ctx, orgID, userID, role)
}

// GetUnreadNotifications mocks base method.
func (m *MockService) GetUnreadNotifications(ctx context.Context, orgID int32) ([]Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadNotifications", ctx, orgID)
	ret0, _ := ret[0].([]Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadNotifications indicates an expected call of GetUnreadNotifications.
func (mr *MockServiceMockRecorder) GetUnreadNotifications(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadNotifications", reflect.TypeOf((*MockService)(nil).GetUnreadNotifications), ctx, orgID)
}

// ListEscalations mocks base method.
func (m *MockService) ListEscalations(ctx context.Context, orgID int64, limit int) ([]EscalationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEscalations", ctx, orgID, limit)
	ret0, _ := ret[0].([]EscalationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEscalations indicates an expected call of ListEscalations.
func (mr *MockServiceMockRecorder) ListEscalations(ctx, orgID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEscalations", reflect.TypeOf((*MockService)(nil).ListEscalations), ctx, orgID, limit)
}

// ListNotifications mocks base method.
func (m *MockService) ListNotifications(ctx context.Context, filter NotificationFilter) ([]Notification, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, filter)
	ret0, _ := ret[0].([]Notification)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockServiceMockRecorder) ListNotifications(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockService)(nil).ListNotifications), ctx, filter)
}

// MarkAllAsRead mocks base method.
func (m *MockService) MarkAllAsRead(ctx context.Context, orgID, userID int64, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, orgID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockServiceMockRecorder) MarkAllAsRead(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockService)(nil).MarkAllAsRead), ctx, orgID, userID, role)
}

// MarkAsRead mocks base method.
func (m *MockService) MarkAsRead(ctx context.Context, orgID, notifID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, orgID, notifID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockServiceMockRecorder) MarkAsRead(ctx, orgID, notifID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockService)(nil).MarkAsRead), ctx, orgID, notifID)
}

// MarkRead mocks base method.
func (m *MockService) MarkRead(ctx context.Context, orgID, id int64, read bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, orgID, id, read)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockServiceMockRecorder) MarkRead(ctx, orgID, id, read any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockService)(nil).MarkRead), ctx, orgID, id, read)
}

// SendEmail mocks base method.
func (m *MockService) SendEmail(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockServiceMockRecorder) SendEmail(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockService)(nil).SendEmail), ctx, to, subject, body)
}

// SendInviteEmail mocks base method.
func (m *MockService) SendInviteEmail(ctx context.Context, toEmail, token, orgName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInviteEmail", ctx, toEmail, token, orgName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInviteEmail indicates an expected call of SendInviteEmail.
func (mr *MockServiceMockRecorder) SendInviteEmail(ctx, toEmail, token, orgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInviteEmail", reflect.TypeOf((*MockService)(nil).SendInviteEmail), ctx, toEmail, token, orgName)
}

// SendWhatsApp mocks base method.
func (m *MockService) SendWhatsApp(ctx context.Context, phone, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWhatsApp", ctx, phone, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWhatsApp indicates an expected call of SendWhatsApp.
func (mr *MockServiceMockRecorder) SendWhatsApp(ctx, phone, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWhatsApp", reflect.TypeOf((*MockService)(nil).SendWhatsApp), ctx, phone, message)
}

// SetApprovalsService mocks base method.
func (m *MockService) SetApprovalsService(appr approvals.Service) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetApprovalsService", appr)
}

// SetApprovalsService indicates an expected call of SetApprovalsService.
func (mr *MockServiceMockRecorder) SetApprovalsService(appr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApprovalsService", reflect.TypeOf((*MockService)(nil).SetApprovalsService), appr)
}

// Snooze mocks base method.
func (m *MockService) Snooze(ctx context.Context, orgID, id int64, durationMinutes int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snooze", ctx, orgID, id, durationMinutes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Snooze indicates an expected call of Snooze.
func (mr *MockServiceMockRecorder) Snooze(ctx, orgID, id, durationMinutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snooze", reflect.TypeOf((*MockService)(nil).Snooze), ctx, orgID, id, durationMinutes)
}

// UpdatePreferences mocks base method.
func (m *MockService) UpdatePreferences(ctx context.Context, prefs *UserNotificationPreferences) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", ctx, prefs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockServiceMockRecorder) UpdatePreferences(ctx, prefs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockService)(nil).UpdatePreferences), ctx, prefs)
}
