// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/notifications/service.go -destination=internal/notifications/mock_service.go -package=notifications
//

// Package notifications is a generated GoMock package.
package notifications

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetUnreadNotifications mocks base method.
func (m *MockService) GetUnreadNotifications(ctx context.Context, orgID int32) ([]Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadNotifications", ctx, orgID)
	ret0, _ := ret[0].([]Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadNotifications indicates an expected call of GetUnreadNotifications.
func (mr *MockServiceMockRecorder) GetUnreadNotifications(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadNotifications", reflect.TypeOf((*MockService)(nil).GetUnreadNotifications), ctx, orgID)
}

// MarkAsRead mocks base method.
func (m *MockService) MarkAsRead(ctx context.Context, orgID, notifID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, orgID, notifID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockServiceMockRecorder) MarkAsRead(ctx, orgID, notifID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockService)(nil).MarkAsRead), ctx, orgID, notifID)
}

// SendEmail mocks base method.
func (m *MockService) SendEmail(ctx context.Context, to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockServiceMockRecorder) SendEmail(ctx, to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockService)(nil).SendEmail), ctx, to, subject, body)
}

// SendInviteEmail mocks base method.
func (m *MockService) SendInviteEmail(ctx context.Context, toEmail, token, orgName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInviteEmail", ctx, toEmail, token, orgName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInviteEmail indicates an expected call of SendInviteEmail.
func (mr *MockServiceMockRecorder) SendInviteEmail(ctx, toEmail, token, orgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInviteEmail", reflect.TypeOf((*MockService)(nil).SendInviteEmail), ctx, toEmail, token, orgName)
}

// SendWhatsApp mocks base method.
func (m *MockService) SendWhatsApp(ctx context.Context, phone, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWhatsApp", ctx, phone, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWhatsApp indicates an expected call of SendWhatsApp.
func (mr *MockServiceMockRecorder) SendWhatsApp(ctx, phone, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWhatsApp", reflect.TypeOf((*MockService)(nil).SendWhatsApp), ctx, phone, message)
}
