import os
import httpx
from langchain_core.tools import tool

# Retrieve the backend location and security keys from environment parameters.
go_backend_url = os.getenv("GO_BACKEND_URL", "http://localhost:8080")
service_token = os.getenv("INTERNAL_SERVICE_TOKEN", "internal-service-key-logisticshq")

@tool
def get_rfq_details_tool(rfq_id: int, org_id: int = 1) -> str:
	"""
	Fetch structural RFQ details (such as origin, destination, incoterms, weight, volume, commodity)
	from the LogisticsHQ backend.
	Use this tool at the start of the pricing agent workflow to inspect what needs pricing.
	"""
	url = f"{go_backend_url}/internal/rfqs/{rfq_id}"
	headers = {"X-LogisticsHQ-Service-Key": service_token}
	params = {"org_id": org_id}
	
	try:
		response = httpx.get(url, params=params, headers=headers, timeout=5.0)
		if response.status_code == 200:
			return response.text
		return f"Error: Backend API responded with status {response.status_code}: {response.text}"
	except Exception as e:
		return f"Failed to connect to Go backend RFQ API: {str(e)}"

@tool
def search_rates_tool(origin: str, destination: str, equipment_type: str = "40GP", incoterms: str = "", org_id: int = 1) -> str:
	"""
	Lookup confirmed contract rates and live spot rates matching origin, destination, and equipment.
	Use this tool to find matching candidate rate offers.
	"""
	url = f"{go_backend_url}/internal/rates/search"
	headers = {"X-LogisticsHQ-Service-Key": service_token}
	params = {
		"org_id": org_id,
		"origin": origin,
		"destination": destination,
		"equipment": equipment_type,
		"incoterms": incoterms
	}
	
	try:
		response = httpx.get(url, params=params, headers=headers, timeout=5.0)
		if response.status_code == 200:
			return response.text
		return f"Error: Backend API responded with status {response.status_code}: {response.text}"
	except Exception as e:
		return f"Failed to connect to Go backend rates search API: {str(e)}"

@tool
def get_pricing_rules_tool(org_id: int = 1, origin: str = "", destination: str = "", tier: str = "", equipment: str = "") -> str:
	"""
	Retrieve active markup and margin rules configured for this organization matching the context.
	Use this tool to evaluate markups and minimum margin requirements before recommending final prices.
	"""
	url = f"{go_backend_url}/internal/pricing/rules"
	headers = {"X-LogisticsHQ-Service-Key": service_token}
	params = {
		"org_id": org_id,
		"origin": origin,
		"destination": destination,
		"tier": tier,
		"equipment": equipment
	}
	
	try:
		response = httpx.get(url, params=params, headers=headers, timeout=5.0)
		if response.status_code == 200:
			return response.text
		return f"Error: Backend API responded with status {response.status_code}: {response.text}"
	except Exception as e:
		return f"Failed to connect to Go backend pricing rules API: {str(e)}"

@tool
def save_draft_quotes_tool(rfq_id: int, quotes: list, org_id: int = 1) -> str:
	"""
	Save draft quotations generated by the pricing engine back to the Go backend system of record.
	Each quote in the list should match the schema:
	{
	  "carrier_name": "Maersk",
	  "transit_time_days": 14,
	  "buy_price": 2800.0,
	  "sell_price": 3360.0,
	  "is_recommended": true,
	  "reliability_score": 90,
	  "historical_success_rate": 0.95,
	  "ai_reasoning": "Excellent rate with short transit."
	}
	"""
	url = f"{go_backend_url}/internal/pricing/quotes/draft"
	headers = {
		"X-LogisticsHQ-Service-Key": service_token,
		"Content-Type": "application/json"
	}
	payload = {
		"rfq_id": rfq_id,
		"org_id": org_id,
		"quotes": quotes
	}
	
	try:
		response = httpx.post(url, json=payload, headers=headers, timeout=5.0)
		if response.status_code == 200:
			return "Success: Draft quotes saved successfully."
		return f"Error: Backend API responded with status {response.status_code}: {response.text}"
	except Exception as e:
		return f"Failed to connect to Go backend quotes draft API: {str(e)}"
