export const INITIAL_APPROVAL_STATS = {
  pending: 12,
  pendingTrend: '↑ 3 from last 7 days',
  approved: 28,
  approvedTrend: '↑ 8 from last 7 days',
  rejected: 4,
  rejectedTrend: '↓ 2 from last 7 days',
  overdue: 3,
};

export const INITIAL_APPROVALS = [
  {
    id: 'DOC-APP-1247',
    title: 'House Bill of Lading - SHP-250812',
    category: 'DOCUMENTS',
    type: 'Document Approval',
    relatedRef: 'Shipment: SHP-250812',
    relatedType: 'Shipment',
    customerName: 'ABC Exports Pvt Ltd',
    requesterName: 'Arjun Singh',
    department: 'Operations',
    avatar: 'AS',
    dueDate: 'Aug 12, 2026',
    dueText: 'Overdue',
    status: 'Overdue',
    priority: 'HIGH',
    description: 'House Bill of Lading requires manager sign-off for container release at Mumbai port.',
    createdAt: '2026-08-09T10:30:00Z',
  },
  {
    id: 'DOC-APP-1246',
    title: 'Commercial Invoice - INV-10293',
    category: 'DOCUMENTS',
    type: 'Document Approval',
    relatedRef: 'Shipment: SHP-250799',
    relatedType: 'Shipment',
    customerName: 'XYZ Logistics Inc.',
    requesterName: 'Neha Kapoor',
    department: 'Documentation',
    avatar: 'NK',
    dueDate: 'Aug 16, 2026',
    dueText: '2 days left',
    status: 'Pending',
    priority: 'MEDIUM',
    description: 'Commercial invoice discrepancy check required before customs clearance filing.',
    createdAt: '2026-08-10T14:15:00Z',
  },
  {
    id: 'COM-APP-0891',
    title: 'Credit Limit Increase Request',
    category: 'COMMERCIAL',
    type: 'Commercial Approval',
    relatedRef: 'Customer: CUST-00734',
    relatedType: 'Customer',
    customerName: 'Global Auto Movers',
    requesterName: 'Rohit Mehta',
    department: 'Sales',
    avatar: 'RM',
    dueDate: 'Aug 18, 2026',
    dueText: '4 days left',
    status: 'Pending',
    priority: 'HIGH',
    description: 'Request to increase credit limit from $50,000 to $100,000 for peak season volume.',
    createdAt: '2026-08-11T09:00:00Z',
  },
  {
    id: 'OPS-APP-0562',
    title: 'Rate Exception - SHP-250788',
    category: 'OPERATIONS',
    type: 'Operations Approval',
    relatedRef: 'Shipment: SHP-250788',
    relatedType: 'Shipment',
    customerName: 'Oceanic Freight Co.',
    requesterName: 'Pooja Shah',
    department: 'Operations',
    avatar: 'PS',
    dueDate: 'Aug 20, 2026',
    dueText: '6 days left',
    status: 'Pending',
    priority: 'MEDIUM',
    description: 'Demurrage waiver request due to port congestion delay at Nhava Sheva.',
    createdAt: '2026-08-12T11:45:00Z',
  },
  {
    id: 'FIN-APP-0321',
    title: 'Invoice Discount Approval',
    category: 'FINANCE',
    type: 'Finance Approval',
    relatedRef: 'Invoice: INV-10277',
    relatedType: 'Invoice',
    customerName: 'Blue Sky Imports',
    requesterName: 'Vikram Kumar',
    department: 'Finance',
    avatar: 'VK',
    dueDate: 'Aug 21, 2026',
    dueText: '7 days left',
    status: 'Pending',
    priority: 'LOW',
    description: '5% early payment discount authorization for key customer invoice INV-10277.',
    createdAt: '2026-08-13T16:20:00Z',
  },
  {
    id: 'DOC-APP-1245',
    title: 'Packing List - SHP-250812',
    category: 'DOCUMENTS',
    type: 'Document Approval',
    relatedRef: 'Shipment: SHP-250812',
    relatedType: 'Shipment',
    customerName: 'ABC Exports Pvt Ltd',
    requesterName: 'Arjun Singh',
    department: 'Operations',
    avatar: 'AS',
    dueDate: 'Aug 21, 2026',
    dueText: '8 days left',
    status: 'Pending',
    priority: 'LOW',
    description: 'Cargo weight verification against packing list data.',
    createdAt: '2026-08-13T17:00:00Z',
  },
  {
    id: 'DOC-APP-1240',
    title: 'Master Bill of Lading - SHP-250750',
    category: 'DOCUMENTS',
    type: 'Document Approval',
    relatedRef: 'Shipment: SHP-250750',
    relatedType: 'Shipment',
    customerName: 'Indo-US Traders',
    requesterName: 'Arjun Singh',
    department: 'Operations',
    avatar: 'AS',
    dueDate: 'Aug 05, 2026',
    dueText: 'Approved',
    status: 'Approved',
    priority: 'HIGH',
    description: 'MBL carrier release verified and approved.',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'COM-APP-0880',
    title: 'Special Spot Quotation Pricing',
    category: 'COMMERCIAL',
    type: 'Commercial Approval',
    relatedRef: 'Quotation: QT-9912',
    relatedType: 'Quotation',
    customerName: 'Pacific Rim Corp',
    requesterName: 'Rohit Mehta',
    department: 'Sales',
    avatar: 'RM',
    dueDate: 'Aug 04, 2026',
    dueText: 'Rejected',
    status: 'Rejected',
    priority: 'HIGH',
    description: 'Requested rate below minimum margin threshold.',
    createdAt: '2026-08-02T13:30:00Z',
  },
];
