-- Seed realistic demo requests for SPortal Demo Requests management
USE freel_mysql;

DELETE FROM demo_requests;

INSERT INTO demo_requests (
    id, full_name, email, company_name, phone, country,
    company_size, message, shipment_volume, services,
    status, notes, assigned_to, source, ip_address, user_agent,
    contacted_at, converted_at, created_at, updated_at
) VALUES
(
    1,
    'Sarah Jenkins',
    'sarah.jenkins@apexglobalfreight.com',
    'Apex Global Freight Solutions',
    '+1 (555) 234-8901',
    'United States',
    '201-500',
    'We manage high-frequency transpacific lanes and need autonomous RFQ pricing along with live container milestone synchronization into our TMS.',
    '500-1000 containers / month',
    'Ocean Freight (FCL/LCL), Autonomous RFQ & Pricing, End-to-End Container Tracking',
    'NEW',
    'Inbound lead from website demo page. High volume enterprise prospect.',
    'Admin Super',
    'WEBSITE_DEMO_PAGE',
    '198.51.100.42',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0.0.0',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL 25 MINUTE),
    DATE_SUB(NOW(), INTERVAL 25 MINUTE)
),
(
    2,
    'David Miller',
    'dmiller@transpacificforwarding.com',
    'TransPacific Forwarders Ltd',
    '+1 (415) 890-1234',
    'Canada',
    '51-200',
    'Interested in AI quotation turnaround speeds and cross-border road freight visibility for our North American corridors.',
    '200-500 shipments / month',
    'Cross-border Road Freight, Air Cargo & Express, Autonomous RFQ & Pricing',
    'NEW',
    'Requested immediate product demo session for their operations VP.',
    NULL,
    'WEBSITE_DEMO_PAGE',
    '198.51.100.77',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL 2 HOUR),
    DATE_SUB(NOW(), INTERVAL 2 HOUR)
),
(
    3,
    'Elena Rostova',
    'e.rostova@vanguard-logistics.eu',
    'Vanguard European Logistics BV',
    '+31 20 555 4321',
    'Netherlands',
    '501-1000',
    'Evaluating LogisticsHQ as our primary customer portal and exception management engine across our Rotterdam and Antwerp hubs.',
    '1500+ shipments / month',
    'Ocean Freight (FCL/LCL), Freight Audit & Invoicing, ERP / TMS Integration (API/EDI)',
    'CONTACTED',
    'Initial discovery call conducted on Zoom. Strong fit for Enterprise Tier. Next meeting scheduled with Head of Procurement.',
    'Admin Super',
    'WEBSITE_DEMO_PAGE',
    '82.165.197.1',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/129.0',
    DATE_SUB(NOW(), INTERVAL 1 DAY),
    NULL,
    DATE_SUB(NOW(), INTERVAL 2 DAY),
    DATE_SUB(NOW(), INTERVAL 1 DAY)
),
(
    4,
    'Marcus Chen',
    'marcus.chen@pacifichorizon.sg',
    'Pacific Horizon Ocean Carriers',
    '+65 6789 0123',
    'Singapore',
    '1000+',
    'Need custom carrier gateway integrations and automated HS tariff classification for intra-Asia sea freight.',
    '3000+ TEU / month',
    'Ocean Freight (FCL/LCL), Customs Clearance & HS Tariff, End-to-End Container Tracking',
    'QUALIFIED',
    'Security & SLA review underway. Custom integration architecture sent to client engineering team.',
    'Admin Super',
    'WEBSITE_DEMO_PAGE',
    '103.252.200.12',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0.0.0',
    DATE_SUB(NOW(), INTERVAL 3 DAY),
    NULL,
    DATE_SUB(NOW(), INTERVAL 4 DAY),
    DATE_SUB(NOW(), INTERVAL 6 HOUR)
),
(
    5,
    'Amit Patel',
    'amit@zenithfreight.in',
    'Zenith Freight Global Pvt Ltd',
    '+91 22 4567 8901',
    'India',
    '51-200',
    'We are scaling rapidly across Nhava Sheva and Mundra ports and need automated freight invoicing and multi-tenant portal capability.',
    '300-600 shipments / month',
    'Ocean Freight (FCL/LCL), Freight Audit & Invoicing, Autonomous RFQ & Pricing',
    'CONVERTED',
    'Contract signed! Organization onboarded to LogisticsHQ as tenant organization #3.',
    'Admin Super',
    'WEBSITE_DEMO_PAGE',
    '115.240.90.15',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0',
    DATE_SUB(NOW(), INTERVAL 5 DAY),
    DATE_SUB(NOW(), INTERVAL 1 DAY),
    DATE_SUB(NOW(), INTERVAL 7 DAY),
    DATE_SUB(NOW(), INTERVAL 1 DAY)
),
(
    6,
    'Lucas Moreira',
    'lucas.m@brasilcargo.com.br',
    'Brasil Cargo & Logistica',
    '+55 11 98765-4321',
    'Brazil',
    '11-50',
    'Testing out the platform for regional Santos port customs and container monitoring.',
    '50-100 shipments / month',
    'Ocean Freight (FCL/LCL), End-to-End Container Tracking',
    'NEW',
    'Awaiting initial phone outreach.',
    NULL,
    'WEBSITE_DEMO_PAGE',
    '177.18.90.22',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15',
    NULL,
    NULL,
    DATE_SUB(NOW(), INTERVAL 3 HOUR),
    DATE_SUB(NOW(), INTERVAL 3 HOUR)
);
