import api from './api';

export const automationService = {
  /**
   * List workflow automations with optional filtering and pagination
   */
  async listAutomations(params = {}) {
    const query = new URLSearchParams();
    if (params.page) query.append('page', params.page);
    if (params.limit) query.append('limit', params.limit);
    if (params.type) query.append('type', params.type);
    if (params.is_enabled !== undefined && params.is_enabled !== '') {
      query.append('is_enabled', params.is_enabled);
    }
    if (params.search) query.append('search', params.search);

    const qs = query.toString();
    const endpoint = qs ? `/api/v1/automations?${qs}` : '/api/v1/automations';
    return await api.get(endpoint);
  },

  /**
   * Get single automation by ID
   */
  async getAutomation(id) {
    return await api.get(`/api/v1/automations/${id}`);
  },

  /**
   * Create a new controlled automation
   */
  async createAutomation(data) {
    return await api.post('/api/v1/automations', data);
  },

  /**
   * Update existing automation definition
   */
  async updateAutomation(id, data) {
    return await api.put(`/api/v1/automations/${id}`, data);
  },

  /**
   * Delete an automation
   */
  async deleteAutomation(id) {
    return await api.delete(`/api/v1/automations/${id}`);
  },

  /**
   * Enable automation
   */
  async enableAutomation(id) {
    return await api.post(`/api/v1/automations/${id}/enable`, {});
  },

  /**
   * Disable automation
   */
  async disableAutomation(id) {
    return await api.post(`/api/v1/automations/${id}/disable`, {});
  },

  /**
   * Preview next scheduled run
   */
  async previewNextRun(id) {
    return await api.get(`/api/v1/automations/${id}/preview-next`);
  },

  /**
   * Trigger immediate manual run
   */
  async runAutomation(id) {
    return await api.post(`/api/v1/automations/${id}/run`, {});
  },

  /**
   * List execution history
   */
  async listExecutions(params = {}) {
    const query = new URLSearchParams();
    if (params.page) query.append('page', params.page);
    if (params.limit) query.append('limit', params.limit);
    if (params.automation_id) query.append('automation_id', params.automation_id);
    if (params.status) query.append('status', params.status);
    if (params.trigger_type) query.append('trigger_type', params.trigger_type);

    const qs = query.toString();
    const endpoint = qs ? `/api/v1/automations/executions?${qs}` : '/api/v1/automations/executions';
    return await api.get(endpoint);
  },

  /**
   * Get single execution details
   */
  async getExecution(id) {
    return await api.get(`/api/v1/automations/executions/${id}`);
  },

  /**
   * Cancel queued or running execution
   */
  async cancelExecution(id, reason = '') {
    return await api.post(`/api/v1/automations/executions/${id}/cancel`, { reason });
  },

  /**
   * Get recommendations generated by execution
   */
  async getExecutionRecommendations(id) {
    return await api.get(`/api/v1/automations/executions/${id}/recommendations`);
  },

  /**
   * Get automation KPI stats
   */
  async getStats() {
    return await api.get('/api/v1/automations/stats');
  },

  /**
   * Get supported automation types catalog
   */
  async getSupportedTypes() {
    return await api.get('/api/v1/automations/supported-types');
  },

  /**
   * Retry a failed automation execution
   */
  async retryExecution(id) {
    return await api.post(`/api/v1/automations/executions/${id}/retry`, {});
  },

  /**
   * Get operational insights generated by execution
   */
  async getExecutionInsights(id) {
    return await api.get(`/api/v1/automations/executions/${id}/insights`);
  },

  /**
   * List operational insights feed (Phase 3 Operational Intelligence)
   */
  async listInsights(params = {}) {
    const query = new URLSearchParams();
    if (params.page) query.append('page', params.page);
    if (params.limit) query.append('limit', params.limit);
    if (params.source_module) query.append('source_module', params.source_module);
    if (params.status) query.append('status', params.status);
    if (params.severity) query.append('severity', params.severity);
    if (params.priority) query.append('priority', params.priority);
    if (params.search) query.append('search', params.search);
    if (params.automation_id) query.append('automation_id', params.automation_id);
    if (params.execution_id) query.append('execution_id', params.execution_id);
    if (params.source_record_id) query.append('source_record_id', params.source_record_id);
    if (params.sort_by) query.append('sort_by', params.sort_by);
    if (params.sort_dir) query.append('sort_dir', params.sort_dir);

    const qs = query.toString();
    const endpoint = qs ? `/api/v1/automations/insights?${qs}` : '/api/v1/automations/insights';
    return await api.get(endpoint);
  },

  /**
   * Get single operational insight by ID
   */
  async getInsight(id) {
    return await api.get(`/api/v1/automations/insights/${id}`);
  },

  /**
   * Acknowledge operational insight
   */
  async acknowledgeInsight(id) {
    return await api.post(`/api/v1/automations/insights/${id}/acknowledge`, {});
  },

  /**
   * Dismiss operational insight with operator reason
   */
  async dismissInsight(id, reason = '') {
    return await api.post(`/api/v1/automations/insights/${id}/dismiss`, { reason });
  },

  /**
   * Ingest and evaluate real business event
   */
  async evaluateEvent(data) {
    return await api.post('/api/v1/automations/evaluate', data);
  },
};

