// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rfq/dl.go
//
// Generated by this command:
//
//	mockgen -source=internal/rfq/dl.go -destination=internal/rfq/mocks/mock_dl.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	spec "github.com/freel/backend/internal/rfq/spec"
	gomock "go.uber.org/mock/gomock"
)

// MockDatalayer is a mock of Datalayer interface.
type MockDatalayer struct {
	ctrl     *gomock.Controller
	recorder *MockDatalayerMockRecorder
	isgomock struct{}
}

// MockDatalayerMockRecorder is the mock recorder for MockDatalayer.
type MockDatalayerMockRecorder struct {
	mock *MockDatalayer
}

// NewMockDatalayer creates a new mock instance.
func NewMockDatalayer(ctrl *gomock.Controller) *MockDatalayer {
	mock := &MockDatalayer{ctrl: ctrl}
	mock.recorder = &MockDatalayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatalayer) EXPECT() *MockDatalayerMockRecorder {
	return m.recorder
}

// ApproveQuote mocks base method.
func (m *MockDatalayer) ApproveQuote(ctx context.Context, rfqID, quoteID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveQuote", ctx, rfqID, quoteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveQuote indicates an expected call of ApproveQuote.
func (mr *MockDatalayerMockRecorder) ApproveQuote(ctx, rfqID, quoteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveQuote", reflect.TypeOf((*MockDatalayer)(nil).ApproveQuote), ctx, rfqID, quoteID)
}

// CreateQuote mocks base method.
func (m *MockDatalayer) CreateQuote(ctx context.Context, quote *spec.Quote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuote", ctx, quote)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuote indicates an expected call of CreateQuote.
func (mr *MockDatalayerMockRecorder) CreateQuote(ctx, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuote", reflect.TypeOf((*MockDatalayer)(nil).CreateQuote), ctx, quote)
}

// CreateRFQ mocks base method.
func (m *MockDatalayer) CreateRFQ(ctx context.Context, rfq *spec.RFQ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRFQ", ctx, rfq)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRFQ indicates an expected call of CreateRFQ.
func (mr *MockDatalayerMockRecorder) CreateRFQ(ctx, rfq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRFQ", reflect.TypeOf((*MockDatalayer)(nil).CreateRFQ), ctx, rfq)
}

// CreateRFQItem mocks base method.
func (m *MockDatalayer) CreateRFQItem(ctx context.Context, item *spec.RFQItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRFQItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRFQItem indicates an expected call of CreateRFQItem.
func (mr *MockDatalayerMockRecorder) CreateRFQItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRFQItem", reflect.TypeOf((*MockDatalayer)(nil).CreateRFQItem), ctx, item)
}

// GetQuotesByRFQ mocks base method.
func (m *MockDatalayer) GetQuotesByRFQ(ctx context.Context, rfqID int32) ([]spec.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotesByRFQ", ctx, rfqID)
	ret0, _ := ret[0].([]spec.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotesByRFQ indicates an expected call of GetQuotesByRFQ.
func (mr *MockDatalayerMockRecorder) GetQuotesByRFQ(ctx, rfqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotesByRFQ", reflect.TypeOf((*MockDatalayer)(nil).GetQuotesByRFQ), ctx, rfqID)
}

// GetRFQByID mocks base method.
func (m *MockDatalayer) GetRFQByID(ctx context.Context, orgID, rfqID int32) (*spec.RFQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRFQByID", ctx, orgID, rfqID)
	ret0, _ := ret[0].(*spec.RFQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRFQByID indicates an expected call of GetRFQByID.
func (mr *MockDatalayerMockRecorder) GetRFQByID(ctx, orgID, rfqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRFQByID", reflect.TypeOf((*MockDatalayer)(nil).GetRFQByID), ctx, orgID, rfqID)
}

// ListRFQs mocks base method.
func (m *MockDatalayer) ListRFQs(ctx context.Context, orgID int32, limit, offset int) ([]spec.RFQ, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRFQs", ctx, orgID, limit, offset)
	ret0, _ := ret[0].([]spec.RFQ)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRFQs indicates an expected call of ListRFQs.
func (mr *MockDatalayerMockRecorder) ListRFQs(ctx, orgID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRFQs", reflect.TypeOf((*MockDatalayer)(nil).ListRFQs), ctx, orgID, limit, offset)
}

// UpdateAgentStatus mocks base method.
func (m *MockDatalayer) UpdateAgentStatus(ctx context.Context, orgID, rfqID int32, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentStatus", ctx, orgID, rfqID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentStatus indicates an expected call of UpdateAgentStatus.
func (mr *MockDatalayerMockRecorder) UpdateAgentStatus(ctx, orgID, rfqID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentStatus", reflect.TypeOf((*MockDatalayer)(nil).UpdateAgentStatus), ctx, orgID, rfqID, status)
}

// UpdateStage mocks base method.
func (m *MockDatalayer) UpdateStage(ctx context.Context, orgID, rfqID int32, stage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStage", ctx, orgID, rfqID, stage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStage indicates an expected call of UpdateStage.
func (mr *MockDatalayerMockRecorder) UpdateStage(ctx, orgID, rfqID, stage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStage", reflect.TypeOf((*MockDatalayer)(nil).UpdateStage), ctx, orgID, rfqID, stage)
}
