/**
 * Comprehensive SPortal Offline / Live Demo Datasets
 * Providing full fidelity for Customer 360, Integrations, Carriers, Webhooks,
 * Subscriptions, Users, Documents, Analytics, and AI Administration.
 */

export const MOCK_ORGANIZATIONS = [
  {
    id: 1,
    name: 'Freel Global Logistics Pvt Ltd',
    legal_name: 'Freel Global Logistics Private Limited',
    registration_number: 'CIN-U63090MH2021PTC368920',
    tax_number: 'GSTIN27AABCF1234F1Z5',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Enterprise',
    plan_status: 'Active',
    user_count: 42,
    active_users_count: 42,
    total_users_count: 45,
    primary_contact_email: 'ops@freelglobal.com',
    primary_email: 'ops@freelglobal.com',
    phone_number: '+91 98765 43210',
    website: 'https://freelglobal.com',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: '702 Freight Towers, Andheri East, Mumbai, Maharashtra 400069',
    company_type: 'Private Limited',
    industry: 'Freight Forwarding & Multi-Modal Supply Chain',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2026-11-15',
    health_status: 'Healthy',
    created_at: '2025-01-15T09:00:00Z',
    updated_at: '2026-10-01T12:00:00Z',
  },
  {
    id: 2,
    name: 'LogisticsHQ Dev Org - Varun Logistics',
    legal_name: 'LogisticsHQ Development Organization LLP',
    registration_number: 'LLPIN-AAB-9921',
    tax_number: 'GSTIN27AABCL9921L1Z9',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Enterprise',
    plan_status: 'Active',
    user_count: 28,
    active_users_count: 28,
    total_users_count: 30,
    primary_contact_email: 'dev@logisticshq.in',
    primary_email: 'dev@logisticshq.in',
    phone_number: '+91 98200 11223',
    website: 'https://logisticshq.in',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Sector 11, CBD Belapur, Navi Mumbai 400614',
    company_type: 'Limited Liability Partnership',
    industry: 'Maritime Tech & Logistics Platform Testing',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2026-11-20',
    health_status: 'Healthy',
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2026-10-02T14:30:00Z',
  },
  {
    id: 3,
    name: 'OceanBridge Shipping Solutions',
    legal_name: 'OceanBridge Shipping Solutions LLP',
    registration_number: 'LLPIN-AAO-5541',
    tax_number: 'GSTIN24AAOCB5541O1Z2',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Professional',
    plan_status: 'Active',
    user_count: 18,
    active_users_count: 18,
    total_users_count: 20,
    primary_contact_email: 'director@oceanbridge.in',
    primary_email: 'director@oceanbridge.in',
    phone_number: '+91 79 2658 9012',
    website: 'https://oceanbridge.in',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    address: '404 Maritime Hub, Gandhidham, Gujarat 370201',
    company_type: 'Limited Liability Partnership',
    industry: 'Ocean FCL & NVOCC Operations',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2026-12-05',
    health_status: 'Healthy',
    created_at: '2025-02-10T11:30:00Z',
    updated_at: '2026-09-28T16:00:00Z',
  },
  {
    id: 4,
    name: 'Eastern Freight Lines Corporation',
    legal_name: 'Eastern Freight Lines Corporation Ltd',
    registration_number: 'CIN-U63010WB2019PLC231001',
    tax_number: 'GSTIN19AABCE2310E1Z4',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Enterprise',
    plan_status: 'Active',
    user_count: 45,
    active_users_count: 45,
    total_users_count: 50,
    primary_contact_email: 'accounts@easternfreight.in',
    primary_email: 'accounts@easternfreight.in',
    phone_number: '+91 33 2289 4400',
    website: 'https://easternfreight.in',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    address: '12 Netaji Subhash Road, BBD Bagh, Kolkata 700001',
    company_type: 'Public Limited',
    industry: 'Cross-Border Multi-Modal Logistics',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2026-12-12',
    health_status: 'Needs Attention',
    created_at: '2025-02-28T14:15:00Z',
    updated_at: '2026-09-30T10:15:00Z',
  },
  {
    id: 5,
    name: 'SkyLink Forwarders India',
    legal_name: 'SkyLink Forwarders India Pvt Ltd',
    registration_number: 'CIN-U63030DL2022PTC395511',
    tax_number: 'GSTIN07AABCS3955S1Z8',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Growth',
    plan_status: 'Active',
    user_count: 12,
    active_users_count: 12,
    total_users_count: 14,
    primary_contact_email: 'support@skylink.in',
    primary_email: 'support@skylink.in',
    phone_number: '+91 11 4152 7800',
    website: 'https://skylink.in',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    address: 'Cargo Complex, IGI Airport, New Delhi 110037',
    company_type: 'Private Limited',
    industry: 'Air Freight & Express Cargo Forwarding',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2026-12-20',
    health_status: 'Healthy',
    created_at: '2025-03-05T16:00:00Z',
    updated_at: '2026-10-03T11:00:00Z',
  },
  {
    id: 6,
    name: 'Apex Freight Global',
    legal_name: 'Apex Freight Global Solutions Ltd',
    registration_number: 'CIN-U63040MH2020PLC341209',
    tax_number: 'GSTIN27AABCA3412A1Z1',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Enterprise',
    plan_status: 'Active',
    user_count: 64,
    active_users_count: 64,
    total_users_count: 70,
    primary_contact_email: 'contact@apexlogix.in',
    primary_email: 'contact@apexlogix.in',
    phone_number: '+91 22 6123 9900',
    website: 'https://apexlogix.in',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Level 14, Commercial Tower, BKC, Mumbai 400051',
    company_type: 'Public Limited',
    industry: 'Global Freight Forwarding & Contract Logistics',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2027-01-10',
    health_status: 'Healthy',
    created_at: '2025-03-12T08:30:00Z',
    updated_at: '2026-10-04T09:20:00Z',
  },
  {
    id: 7,
    name: 'TransGlobe Logistics Pvt Ltd',
    legal_name: 'TransGlobe Logistics Private Limited',
    registration_number: 'CIN-U63090TN2021PTC142005',
    tax_number: 'GSTIN33AABCT1420T1Z6',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Professional',
    plan_status: 'Active',
    user_count: 32,
    active_users_count: 32,
    total_users_count: 35,
    primary_contact_email: 'ops@transglobe.in',
    primary_email: 'ops@transglobe.in',
    phone_number: '+91 44 2534 8811',
    website: 'https://transglobe.in',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    address: 'Port Gateway Centre, Rajaji Salai, Chennai 600001',
    company_type: 'Private Limited',
    industry: 'Port Operations & Coastal Shipping',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2027-01-15',
    health_status: 'Healthy',
    created_at: '2025-01-15T09:00:00Z',
    updated_at: '2026-09-15T15:45:00Z',
  },
  {
    id: 8,
    name: 'Shreeji Multi-Modal Freight',
    legal_name: 'Shreeji Multi-Modal Freight Ltd',
    registration_number: 'CIN-U63090GJ2023PLC140221',
    tax_number: 'GSTIN24AABCS1402S1Z3',
    status: 'Active',
    onboarding_status: 'COMPLETED',
    plan_name: 'Starter',
    plan_status: 'Active',
    user_count: 8,
    active_users_count: 8,
    total_users_count: 10,
    primary_contact_email: 'info@shreejifreight.in',
    primary_email: 'info@shreejifreight.in',
    phone_number: '+91 2836 231450',
    website: 'https://shreejifreight.in',
    city: 'Kandla',
    state: 'Gujarat',
    country: 'India',
    address: 'Kandla Port Road, Gandhidham 370205',
    company_type: 'Public Limited',
    industry: 'Bulk Cargo & Multi-Modal Surface Transport',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: '2027-01-22',
    health_status: 'Healthy',
    created_at: '2025-03-20T10:00:00Z',
    updated_at: '2026-09-22T11:10:00Z',
  },
  {
    id: 9,
    name: 'Vardhan Freight & Customs Services',
    legal_name: 'Vardhan Freight & Customs Services',
    registration_number: 'CIN-U63090MH2024PTC419870',
    tax_number: 'GSTIN27AABCV4198V1Z7',
    status: 'Trial',
    onboarding_status: 'IN_PROGRESS',
    plan_name: 'Growth',
    plan_status: 'Trial',
    user_count: 6,
    active_users_count: 6,
    total_users_count: 6,
    primary_contact_email: 'contact@vardhanfreight.com',
    primary_email: 'contact@vardhanfreight.com',
    phone_number: '+91 22 2789 6540',
    website: 'https://vardhanfreight.com',
    city: 'Nhava Sheva',
    state: 'Maharashtra',
    country: 'India',
    address: 'JNPT SEZ Road, Uran, Navi Mumbai 400702',
    company_type: 'Private Limited',
    industry: 'Customs Broking & Port Drayage',
    default_currency: 'USD',
    default_timezone: 'Asia/Kolkata',
    renewal_date: null,
    health_status: 'Needs Attention',
    created_at: '2025-04-01T12:00:00Z',
    updated_at: '2026-10-01T17:00:00Z',
  },
];

export const MOCK_OVERVIEW = {
  total_organizations: 48,
  active_organizations: 42,
  trial_organizations: 6,
  total_users: 312,
  active_users: 284,
  mrr: 1420000,
  arr: 17040000,
  net_revenue_retention: 118,
  platform_health_score: 96.4,
  upcoming_renewals: [
    { org_id: 1, org_name: 'Freel Global Logistics Pvt Ltd', amount: 1299, current_period_end: '2026-11-15', days_left: 37 },
    { org_id: 2, org_name: 'LogisticsHQ Dev Org - Varun Logistics', amount: 999, current_period_end: '2026-11-20', days_left: 42 },
    { org_id: 3, org_name: 'OceanBridge Shipping Solutions', amount: 599, current_period_end: '2026-12-05', days_left: 57 },
    { org_id: 4, org_name: 'Eastern Freight Lines', amount: 1299, current_period_end: '2026-12-12', days_left: 64 },
    { org_id: 5, org_name: 'SkyLink Forwarders India', amount: 399, current_period_end: '2026-12-20', days_left: 72 },
  ],
};

export const MOCK_CARRIER_CATALOG = [
  { provider_name: 'MAEU', display_name: 'A.P. Moller – Maersk', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'MSCU', display_name: 'Mediterranean Shipping Company (MSC)', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'HLCU', display_name: 'Hapag-Lloyd', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'CMA_CGM', display_name: 'CMA CGM Group', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'ONE', display_name: 'Ocean Network Express (ONE)', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'EVERGREEN', display_name: 'Evergreen Marine Corporation', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'AVAILABLE', is_configured: false },
  { provider_name: 'COSCO', display_name: 'COSCO Shipping Lines', category: 'CARRIER', supported_protocols: ['REST', 'EDI_214'], status: 'AVAILABLE', is_configured: false },
  { provider_name: 'DHL', display_name: 'DHL Global Forwarding', category: 'CARRIER', supported_protocols: ['REST API'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'FEDEX', display_name: 'FedEx Trade Networks', category: 'CARRIER', supported_protocols: ['REST API'], status: 'CONNECTED', is_configured: true },
  { provider_name: 'UPS', display_name: 'UPS Supply Chain Solutions', category: 'CARRIER', supported_protocols: ['REST API'], status: 'CONNECTED', is_configured: true },
];

export const MOCK_INTEGRATION_ITEMS = [
  {
    id: 101,
    category: 'CARRIER',
    provider_name: 'MAEU',
    display_name: 'A.P. Moller – Maersk Line',
    description: 'Direct REST API & EDI 214 liner connection for instant spot booking, container milestone tracking, and sea waybill retrieval.',
    business_purpose: 'Automated container tracking, live vessel schedules, and e-booking dispatch.',
    dependent_workflows: ['Automated Tracking', 'Rate Quoting', 'Instant Booking', 'Sea Waybill OCR'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { connection_method: 'REST API & OAuth 2.0', endpoint: 'https://api.maersk.com/ocean/v1', client_id: 'freel-maersk-prod-****' },
    last_synced_at: '2026-10-09T05:30:00Z',
    last_success_at: '2026-10-09T05:30:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 4210,
    failure_count_30d: 2,
    health_score: 98,
    health_message: 'Healthy connection • 142ms latency via TLS 1.3',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
  {
    id: 102,
    category: 'CARRIER',
    provider_name: 'HLCU',
    display_name: 'Hapag-Lloyd Direct Gateway',
    description: 'DCSA-compliant container track & trace, point-to-point commercial schedules, and contract rate discovery.',
    business_purpose: 'Container milestone synchronization and schedule discovery across Asia-Europe routes.',
    dependent_workflows: ['Tracking', 'Schedules', 'Milestone Alerts'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { connection_method: 'REST API Key', endpoint: 'https://api-portal.hlag.com/v1', api_key_mask: 'hlag_sec_****' },
    last_synced_at: '2026-10-09T05:15:00Z',
    last_success_at: '2026-10-09T05:15:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 2840,
    failure_count_30d: 0,
    health_score: 96,
    health_message: 'Active • 120ms round-trip latency verified',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
  {
    id: 103,
    category: 'CARRIER',
    provider_name: 'MSCU',
    display_name: 'Mediterranean Shipping Company (MSC)',
    description: 'Direct ocean liner API for container milestone events, shipping orders, and spot booking requests.',
    business_purpose: 'End-to-end container milestone events and booking dispatch.',
    dependent_workflows: ['Milestones', 'Spot Rates', 'Booking Dispatch'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { connection_method: 'API (OAuth 2.0)', endpoint: 'https://api.msc.com/v2', client_id: 'msc_freel_****' },
    last_synced_at: '2026-10-09T04:45:00Z',
    last_success_at: '2026-10-09T04:45:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 3105,
    failure_count_30d: 1,
    health_score: 95,
    health_message: 'Operational • Synchronized 45 min ago',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
  {
    id: 104,
    category: 'CARRIER',
    provider_name: 'ONE',
    display_name: 'Ocean Network Express (ONE)',
    description: 'Magenta liner tracking API for Far East and Transpacific containerized freight tracking.',
    business_purpose: 'Real-time telemetry and booking validation for ONE vessels.',
    dependent_workflows: ['Tracking', 'Booking Confirmation'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { connection_method: 'REST API', endpoint: 'https://api.one-line.com/v1', api_key_mask: 'one_live_****' },
    last_synced_at: '2026-10-09T03:30:00Z',
    last_success_at: '2026-10-09T03:30:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 1540,
    failure_count_30d: 0,
    health_score: 94,
    health_message: 'Connected • Far East network verified',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
  {
    id: 105,
    category: 'CARRIER',
    provider_name: 'CMA_CGM',
    display_name: 'CMA CGM Group',
    description: 'Carrier API integration for Mediterranean and European multi-modal routing.',
    business_purpose: 'Quoting and container tracking across French and European hubs.',
    dependent_workflows: ['Tracking', 'Rate Quoting'],
    status: 'CONFIGURATION_REQUIRED',
    is_enabled: true,
    is_configured: false,
    environment: 'SANDBOX',
    credential_state: 'MISSING',
    safe_config: { connection_method: 'REST API (OAuth 2.0)', endpoint: 'https://apis.cma-cgm.com/v1' },
    last_synced_at: null,
    last_success_at: null,
    last_failure_at: '2026-10-08T18:00:00Z',
    last_error: 'Credentials pending client secret activation in production',
    sync_status: 'IDLE',
    event_count_30d: 0,
    failure_count_30d: 1,
    health_score: 55,
    health_message: 'Configuration Required • Client secret not provisioned',
    can_test: true,
    can_sync: false,
    can_toggle: true,
  },
  {
    id: 106,
    category: 'STORAGE',
    provider_name: 'AWS_S3',
    display_name: 'Amazon S3 Document Vault',
    description: 'Tenant-isolated AWS S3 freight document vault bucket freel-platform-documents-production.',
    business_purpose: 'Secure, encrypted storage for Bills of Lading, packing lists, commercial invoices, and customs bills.',
    dependent_workflows: ['Document Vault', 'OCR Pipeline', 'Compliance Archival'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { bucket: 'freel-platform-documents-production', region: 'ap-south-1', encryption: 'AES-256' },
    last_synced_at: '2026-10-09T05:40:00Z',
    last_success_at: '2026-10-09T05:40:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 8940,
    failure_count_30d: 0,
    health_score: 100,
    health_message: 'Connected • Encrypted bucket operational on ap-south-1',
    can_test: true,
    can_sync: true,
    can_toggle: false,
  },
  {
    id: 107,
    category: 'TEXTRACT',
    provider_name: 'AWS_TEXTRACT',
    display_name: 'AWS Textract Neural OCR',
    description: 'Neural document extraction and table parsing for Bill of Lading and shipping contract analysis.',
    business_purpose: 'Automated data ingestion from multi-page PDFs with zero manual keying.',
    dependent_workflows: ['Document Classification', 'Rate Table Extraction', 'Anomaly Detection'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { region: 'ap-south-1', model_version: '2026-Q3-Neural' },
    last_synced_at: '2026-10-09T05:20:00Z',
    last_success_at: '2026-10-09T05:20:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 2190,
    failure_count_30d: 1,
    health_score: 97,
    health_message: 'Active • 99.4% OCR confidence score across 2,190 pages',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
  {
    id: 108,
    category: 'EMAIL',
    provider_name: 'AWS_SES',
    display_name: 'Amazon Simple Email Service (SES)',
    description: 'Enterprise transactional email delivery for shipment milestone alerts, pre-alerts, and invoices.',
    business_purpose: 'Automated customer event notification and pre-alert dispatch.',
    dependent_workflows: ['Pre-Alert Notification', 'Invoice Emailing', 'Exception Alerts'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { verified_identity: 'logisticshq26@gmail.com', region: 'ap-south-1', tls: 'TLS 1.3' },
    last_synced_at: '2026-10-09T05:35:00Z',
    last_success_at: '2026-10-09T05:35:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 5820,
    failure_count_30d: 0,
    health_score: 100,
    health_message: 'Verified Identity • 0.02% bounce rate (Tier 1 reputation)',
    can_test: true,
    can_sync: false,
    can_toggle: true,
  },
  {
    id: 109,
    category: 'SMS',
    provider_name: 'TWILIO',
    display_name: 'Twilio SMS & WhatsApp Gateway',
    description: 'Instant multi-channel SMS and WhatsApp milestone notifications for drivers and dispatchers.',
    business_purpose: 'Driver gate dispatch alerts and critical container delay notifications.',
    dependent_workflows: ['WhatsApp Updates', 'Driver SMS Notifications'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { account_sid: 'AC98271625****', sender_id: 'LOGISTHQ' },
    last_synced_at: '2026-10-09T04:10:00Z',
    last_success_at: '2026-10-09T04:10:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 1420,
    failure_count_30d: 2,
    health_score: 95,
    health_message: 'Active • 99.8% delivery rate via Indian DLT headers',
    can_test: true,
    can_sync: false,
    can_toggle: true,
  },
  {
    id: 110,
    category: 'ACCOUNTING',
    provider_name: 'QUICKBOOKS',
    display_name: 'Intuit QuickBooks Online Accounting',
    description: 'Automated invoice synchronization, accounts receivable tracking, and customer balance reconciliations.',
    business_purpose: 'Real-time billing ledger sync between LogisticsHQ and customer ERP.',
    dependent_workflows: ['Invoice Sync', 'AR Balance Verification', 'Payment Receipts'],
    status: 'CONNECTED',
    is_enabled: true,
    is_configured: true,
    environment: 'PRODUCTION',
    credential_state: 'MASKED',
    safe_config: { connection_method: 'OAuth 2.0', realm_id: 'qb_realm_991827****' },
    last_synced_at: '2026-10-09T05:00:00Z',
    last_success_at: '2026-10-09T05:00:00Z',
    last_failure_at: null,
    last_error: '',
    sync_status: 'SUCCESS',
    event_count_30d: 840,
    failure_count_30d: 0,
    health_score: 98,
    health_message: 'Connected • Ledger synchronized with 0 reconciliation errors',
    can_test: true,
    can_sync: true,
    can_toggle: true,
  },
];

export const MOCK_WEBHOOKS = [
  {
    id: 201,
    scac: 'MAEU',
    event_type: 'CONTAINER_GATE_IN',
    reference_number: 'MSKU9182736',
    booking_number: 'BKG-MAEU-98210',
    received_at: '2026-10-09T05:12:30Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_maeu_9921',
      carrier: 'MAEU',
      timestamp: '2026-10-09T05:10:00Z',
      container_number: 'MSKU9182736',
      milestone: 'GATE_IN',
      location: 'Nhava Sheva (INNSA) APMT Terminal 4',
      vessel: 'MAERSK MC-KINNEY MOLLER',
      voyage: '2604W',
    },
  },
  {
    id: 202,
    scac: 'MSCU',
    event_type: 'VESSEL_DEPARTURE',
    reference_number: 'MSCU8273641',
    booking_number: 'BKG-MSCU-77412',
    received_at: '2026-10-09T04:42:15Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_msc_4401',
      carrier: 'MSCU',
      timestamp: '2026-10-09T04:35:00Z',
      container_number: 'MSCU8273641',
      milestone: 'VESSEL_DEPARTURE',
      origin_port: 'Mundra (INMUN)',
      destination_port: 'Rotterdam (NLRTM)',
      vessel: 'MSC GULSUN',
      voyage: '2610E',
    },
  },
  {
    id: 203,
    scac: 'HLCU',
    event_type: 'CUSTOMS_CLEARED',
    reference_number: 'HLCU7162534',
    booking_number: 'BKG-HLCU-11029',
    received_at: '2026-10-09T03:55:00Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_hlag_8820',
      carrier: 'HLCU',
      timestamp: '2026-10-09T03:50:00Z',
      container_number: 'HLCU7162534',
      milestone: 'CUSTOMS_CLEARED',
      location: 'Hamburg Port (DEHAM) CTA Terminal',
      status_code: 'CC_PASSED',
    },
  },
  {
    id: 204,
    scac: 'MAEU',
    event_type: 'CONTAINER_DISCHARGED',
    reference_number: 'MSKU1029384',
    booking_number: 'BKG-MAEU-66501',
    received_at: '2026-10-09T02:18:40Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_maeu_7712',
      carrier: 'MAEU',
      container_number: 'MSKU1029384',
      milestone: 'DISCHARGED',
      location: 'Jebel Ali Port (AEJEA) Terminal 2',
    },
  },
  {
    id: 205,
    scac: 'ONE',
    event_type: 'TRANSSHIPMENT_LOADED',
    reference_number: 'ONEU6251423',
    booking_number: 'BKG-ONE-33419',
    received_at: '2026-10-08T22:45:10Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_one_5510',
      carrier: 'ONE',
      container_number: 'ONEU6251423',
      milestone: 'TRANSSHIPMENT_LOADED',
      hub: 'Port of Singapore (SGSIN) Pasir Panjang',
      connecting_vessel: 'ONE APUS',
    },
  },
  {
    id: 206,
    scac: 'MSCU',
    event_type: 'GATE_OUT',
    reference_number: 'MSCU5516273',
    booking_number: 'BKG-MSCU-99214',
    received_at: '2026-10-08T19:30:00Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_msc_3391',
      carrier: 'MSCU',
      container_number: 'MSCU5516273',
      milestone: 'GATE_OUT',
      location: 'Rotterdam Port World Gateway',
    },
  },
  {
    id: 207,
    scac: 'HLCU',
    event_type: 'ETA_UPDATED',
    reference_number: 'HLCU8827162',
    booking_number: 'BKG-HLCU-55201',
    received_at: '2026-10-08T16:15:20Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_hlag_1290',
      carrier: 'HLCU',
      milestone: 'ETA_UPDATE',
      original_eta: '2026-10-14T08:00:00Z',
      revised_eta: '2026-10-14T20:00:00Z',
      reason: 'Suez Canal Convoy Rescheduling',
    },
  },
  {
    id: 208,
    scac: 'MAEU',
    event_type: 'BOOKING_CONFIRMED',
    reference_number: 'MSKU4401928',
    booking_number: 'BKG-MAEU-44019',
    received_at: '2026-10-08T12:00:00Z',
    status: 'DELIVERED',
    signature_valid: true,
    payload: {
      event_id: 'evt_maeu_0091',
      carrier: 'MAEU',
      booking_number: 'BKG-MAEU-44019',
      carrier_reference: 'MAEU-BKG-2026-OCT-88',
      equipment: '2 x 40HC High Cube Dry',
      status: 'CONFIRMED',
    },
  },
];

export const MOCK_SYNC_JOBS = [
  {
    id: 301,
    job_name: 'Maersk Container Tracking Poller',
    provider_name: 'MAEU',
    frequency: 'Every 15 min',
    last_run_at: '2026-10-09T05:30:00Z',
    next_run_at: '2026-10-09T05:45:00Z',
    status: 'SUCCESS',
    records_processed: 48,
    avg_latency_ms: 184,
  },
  {
    id: 302,
    job_name: 'MSC Milestone Reconciliation Worker',
    provider_name: 'MSCU',
    frequency: 'Every 30 min',
    last_run_at: '2026-10-09T05:15:00Z',
    next_run_at: '2026-10-09T05:45:00Z',
    status: 'SUCCESS',
    records_processed: 32,
    avg_latency_ms: 210,
  },
  {
    id: 303,
    job_name: 'Hapag-Lloyd Schedule Sync Daemon',
    provider_name: 'HLCU',
    frequency: 'Every 1 hour',
    last_run_at: '2026-10-09T05:00:00Z',
    next_run_at: '2026-10-09T06:00:00Z',
    status: 'SUCCESS',
    records_processed: 120,
    avg_latency_ms: 145,
  },
  {
    id: 304,
    job_name: 'AWS S3 Document Vault Backup',
    provider_name: 'AWS_S3',
    frequency: 'Every 6 hours',
    last_run_at: '2026-10-09T00:00:00Z',
    next_run_at: '2026-10-09T06:00:00Z',
    status: 'SUCCESS',
    records_processed: 215,
    avg_latency_ms: 320,
  },
  {
    id: 305,
    job_name: 'QuickBooks Accounts Receivable Sync',
    provider_name: 'QUICKBOOKS',
    frequency: 'Every 2 hours',
    last_run_at: '2026-10-09T04:00:00Z',
    next_run_at: '2026-10-09T06:00:00Z',
    status: 'SUCCESS',
    records_processed: 18,
    avg_latency_ms: 412,
  },
];

export const MOCK_SHIPMENTS = [
  {
    id: 501,
    booking_number: 'BKG-MAEU-98210',
    carrier_scac: 'MAEU',
    carrier_name: 'Maersk Line',
    vessel_name: 'MAERSK MC-KINNEY MOLLER',
    voyage_number: '2604W',
    origin_port: 'Nhava Sheva (INNSA)',
    destination_port: 'Hamburg (DEHAM)',
    containers_count: 2,
    container_number: 'MSKU9182736',
    status: 'IN_TRANSIT',
    etd: '2026-10-01T10:00:00Z',
    eta: '2026-10-22T18:00:00Z',
    created_at: '2026-09-24T12:00:00Z',
  },
  {
    id: 502,
    booking_number: 'BKG-MSCU-77412',
    carrier_scac: 'MSCU',
    carrier_name: 'MSC',
    vessel_name: 'MSC GULSUN',
    voyage_number: '2610E',
    origin_port: 'Mundra (INMUN)',
    destination_port: 'Rotterdam (NLRTM)',
    containers_count: 4,
    container_number: 'MSCU8273641',
    status: 'DEPARTED',
    etd: '2026-10-05T08:00:00Z',
    eta: '2026-10-25T14:00:00Z',
    created_at: '2026-09-28T09:30:00Z',
  },
  {
    id: 503,
    booking_number: 'BKG-HLCU-11029',
    carrier_scac: 'HLCU',
    carrier_name: 'Hapag-Lloyd',
    vessel_name: 'AL ZUBARA',
    voyage_number: '2602W',
    origin_port: 'Nhava Sheva (INNSA)',
    destination_port: 'Antwerp (BEANR)',
    containers_count: 1,
    container_number: 'HLCU7162534',
    status: 'CUSTOMS_HOLD',
    etd: '2026-09-18T14:00:00Z',
    eta: '2026-10-11T12:00:00Z',
    created_at: '2026-09-12T16:00:00Z',
  },
  {
    id: 504,
    booking_number: 'BKG-MAEU-66501',
    carrier_scac: 'MAEU',
    carrier_name: 'Maersk Line',
    vessel_name: 'MAERSK SEOUL',
    voyage_number: '2608S',
    origin_port: 'Chennai (INMAA)',
    destination_port: 'Jebel Ali (AEJEA)',
    containers_count: 3,
    container_number: 'MSKU1029384',
    status: 'DELIVERED',
    etd: '2026-09-20T06:00:00Z',
    eta: '2026-09-28T18:00:00Z',
    created_at: '2026-09-15T11:20:00Z',
  },
];

export const MOCK_INVOICES = [
  {
    id: 601,
    invoice_number: 'INV-2026-DEV-001',
    customer_name: 'Freel Global Logistics Pvt Ltd',
    total_amount: 14850.00,
    paid_amount: 14850.00,
    balance_due: 0.00,
    currency: 'USD',
    status: 'PAID',
    due_date: '2026-09-30T00:00:00Z',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 602,
    invoice_number: 'INV-2026-OCT-002',
    customer_name: 'Freel Global Logistics Pvt Ltd',
    total_amount: 18400.00,
    paid_amount: 10000.00,
    balance_due: 8400.00,
    currency: 'USD',
    status: 'PARTIALLY_PAID',
    due_date: '2026-10-25T00:00:00Z',
    created_at: '2026-10-01T09:00:00Z',
  },
  {
    id: 603,
    invoice_number: 'INV-2026-OCT-003',
    customer_name: 'Freel Global Logistics Pvt Ltd',
    total_amount: 6250.00,
    paid_amount: 0.00,
    balance_due: 6250.00,
    currency: 'USD',
    status: 'PENDING',
    due_date: '2026-10-31T00:00:00Z',
    created_at: '2026-10-05T14:30:00Z',
  },
];

export const MOCK_CONTRACTS = [
  {
    id: 701,
    contract_reference: 'SC-MAEU-99201-2026',
    contract_name: 'Maersk Line Master Ocean Freight Service Agreement',
    contract_type: 'OCEAN_SERVICE_CONTRACT',
    carrier_name: 'A.P. Moller – Maersk',
    carrier_scac: 'MAEU',
    party_name: 'Freel Global Logistics Pvt Ltd',
    transport_mode: 'OCEAN',
    status: 'ACTIVE',
    contract_value: 320000.00,
    currency: 'USD',
    effective_date: '2026-01-01T00:00:00Z',
    expiry_date: '2026-12-31T00:00:00Z',
    days_to_expiry: 83,
    is_expiring_soon: false,
    is_expired: false,
    owner: 'Varun Kanade',
    description: 'Guaranteed rate tables for Nhava Sheva to Hamburg, Rotterdam, and Jebel Ali.',
    created_at: '2025-12-28T10:00:00Z',
  },
  {
    id: 702,
    contract_reference: 'SC-MSCU-88410-2026',
    contract_name: 'MSC Transpacific & Europe Tier 1 Volume Agreement',
    contract_type: 'OCEAN_VOLUME_COMMITMENT',
    carrier_name: 'Mediterranean Shipping Company (MSC)',
    carrier_scac: 'MSCU',
    party_name: 'Freel Global Logistics Pvt Ltd',
    transport_mode: 'OCEAN',
    status: 'ACTIVE',
    contract_value: 240000.00,
    currency: 'USD',
    effective_date: '2026-03-01T00:00:00Z',
    expiry_date: '2026-11-05T00:00:00Z',
    days_to_expiry: 27,
    is_expiring_soon: true,
    is_expired: false,
    owner: 'Priya Sharma',
    description: 'Annual 500 TEU volume commitment on India-Westbound routes.',
    created_at: '2026-02-25T11:00:00Z',
  },
];

export const MOCK_EXCEPTIONS = [
  {
    id: 801,
    shipment_id: 503,
    booking_number: 'BKG-HLCU-11029',
    exception_type: 'CUSTOMS_INSPECTION_HOLD',
    severity: 'HIGH',
    status: 'OPEN',
    location: 'Antwerp (BEANR)',
    description: 'Physical container inspection flagged by Belgian customs authority for HS Code 8471 verification.',
    assigned_to: 'Priya Sharma',
    created_at: '2026-10-08T14:20:00Z',
    resolved_at: null,
  },
  {
    id: 802,
    shipment_id: 501,
    booking_number: 'BKG-MAEU-98210',
    exception_type: 'PORT_CONGESTION_DELAY',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    location: 'Nhava Sheva (INNSA)',
    description: 'Vessel berthing delayed by 18 hours due to cyclonic weather conditions; revised ETA updated automatically.',
    assigned_to: 'Varun Kanade',
    created_at: '2026-10-02T08:00:00Z',
    resolved_at: '2026-10-03T12:00:00Z',
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 901,
    organization_id: 1,
    file_name: 'HBL_Shipment_101.pdf',
    doc_type: 'BILL_OF_LADING',
    document_type_name: 'House Bill of Lading',
    status: 'VERIFIED',
    verification_status: 'VERIFIED',
    file_size_bytes: 482910,
    file_size: '472 KB',
    content_type: 'application/pdf',
    confidence_score: 99.4,
    s3_key: 'org_1/documents/2026/hbl_101.pdf',
    uploaded_by: 'Varun Kanade',
    created_at: '2026-10-05T09:30:00Z',
    updated_at: '2026-10-05T09:32:00Z',
    extracted_data: {
      shipper: 'Tata Chemicals Ltd, Mumbai',
      consignee: 'EuroChemicals GmbH, Hamburg',
      carrier: 'Maersk Line',
      containers: ['MSKU9182736'],
      gross_weight: '24,500 KG',
    },
  },
  {
    id: 902,
    organization_id: 1,
    file_name: 'Maersk_Contract_2026.pdf',
    doc_type: 'SERVICE_CONTRACT',
    document_type_name: 'Ocean Service Contract',
    status: 'VERIFIED',
    verification_status: 'VERIFIED',
    file_size_bytes: 1240980,
    file_size: '1.2 MB',
    content_type: 'application/pdf',
    confidence_score: 98.8,
    s3_key: 'org_1/documents/2026/maersk_contract.pdf',
    uploaded_by: 'Varun Kanade',
    created_at: '2026-09-15T14:10:00Z',
    updated_at: '2026-09-15T14:15:00Z',
  },
  {
    id: 903,
    organization_id: 1,
    file_name: 'Commercial_Invoice_782.pdf',
    doc_type: 'COMMERCIAL_INVOICE',
    document_type_name: 'Commercial Invoice',
    status: 'VERIFIED',
    verification_status: 'VERIFIED',
    file_size_bytes: 312450,
    file_size: '305 KB',
    content_type: 'application/pdf',
    confidence_score: 99.1,
    s3_key: 'org_1/documents/2026/inv_782.pdf',
    uploaded_by: 'Priya Sharma',
    created_at: '2026-10-01T11:00:00Z',
    updated_at: '2026-10-01T11:02:00Z',
  },
  {
    id: 904,
    organization_id: 1,
    file_name: 'Certificate_of_Origin_INNSA.pdf',
    doc_type: 'CERTIFICATE_OF_ORIGIN',
    document_type_name: 'Certificate of Origin',
    status: 'VERIFIED',
    verification_status: 'VERIFIED',
    file_size_bytes: 284100,
    file_size: '277 KB',
    content_type: 'application/pdf',
    confidence_score: 97.6,
    s3_key: 'org_1/documents/2026/coo_innsa.pdf',
    uploaded_by: 'Priya Sharma',
    created_at: '2026-10-02T16:20:00Z',
    updated_at: '2026-10-02T16:22:00Z',
  },
  {
    id: 905,
    organization_id: 1,
    file_name: 'Packing_List_Container_40GP.pdf',
    doc_type: 'PACKING_LIST',
    document_type_name: 'Packing List',
    status: 'VERIFIED',
    verification_status: 'VERIFIED',
    file_size_bytes: 198400,
    file_size: '194 KB',
    content_type: 'application/pdf',
    confidence_score: 99.0,
    s3_key: 'org_1/documents/2026/packing_list.pdf',
    uploaded_by: 'Amit Patel',
    created_at: '2026-10-04T10:15:00Z',
    updated_at: '2026-10-04T10:16:00Z',
  },
  {
    id: 906,
    organization_id: 1,
    file_name: 'Customs_Declaration_Shipping_Bill.pdf',
    doc_type: 'CUSTOMS_DECLARATION',
    document_type_name: 'Indian Customs Shipping Bill',
    status: 'PENDING_REVIEW',
    verification_status: 'PENDING_REVIEW',
    file_size_bytes: 521000,
    file_size: '508 KB',
    content_type: 'application/pdf',
    confidence_score: 94.2,
    s3_key: 'org_1/documents/2026/shipping_bill.pdf',
    uploaded_by: 'Amit Patel',
    created_at: '2026-10-08T18:00:00Z',
    updated_at: '2026-10-08T18:00:00Z',
  },
];

export const MOCK_USERS = [
  {
    id: 1,
    user_id: 1,
    org_id: 1,
    full_name: 'Varun Kanade',
    email: 'varun@freelglobal.com',
    role: 'SUPER_ADMIN',
    role_name: 'Super Admin',
    status: 'ACTIVE',
    phone: '+91 98765 43210',
    title: 'Managing Director & CEO',
    last_login_at: '2026-10-09T05:30:00Z',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 2,
    user_id: 2,
    org_id: 1,
    full_name: 'Priya Sharma',
    email: 'priya.s@freelglobal.com',
    role: 'OPS_MANAGER',
    role_name: 'Operations Manager',
    status: 'ACTIVE',
    phone: '+91 98200 44332',
    title: 'Head of Ocean Freight Operations',
    last_login_at: '2026-10-09T04:15:00Z',
    created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 3,
    user_id: 3,
    org_id: 1,
    full_name: 'Amit Patel',
    email: 'amit.p@freelglobal.com',
    role: 'DISPATCHER',
    role_name: 'Freight Dispatcher',
    status: 'ACTIVE',
    phone: '+91 98111 88776',
    title: 'Senior CFS & Port Dispatcher',
    last_login_at: '2026-10-08T17:40:00Z',
    created_at: '2025-03-10T11:00:00Z',
  },
  {
    id: 4,
    user_id: 4,
    org_id: 1,
    full_name: 'Sneha Kulkarni',
    email: 'finance@freelglobal.com',
    role: 'BILLING_ADMIN',
    role_name: 'Billing & Finance Admin',
    status: 'ACTIVE',
    phone: '+91 98333 22114',
    title: 'Lead Commercial Controller',
    last_login_at: '2026-10-08T15:20:00Z',
    created_at: '2025-04-05T09:30:00Z',
  },
];

export const MOCK_SUBSCRIPTION_PLANS = [
  {
    id: 1,
    name: 'Starter Forwarder',
    code: 'STARTER_MONTHLY',
    monthly_price: 199,
    annual_price: 1990,
    currency: 'USD',
    features: ['Up to 50 active shipments', '5 team users', 'Standard carrier tracking (Maersk/MSC)', 'Email notifications'],
    is_active: true,
  },
  {
    id: 2,
    name: 'Professional Suite',
    code: 'PROFESSIONAL_MONTHLY',
    monthly_price: 599,
    annual_price: 5990,
    currency: 'USD',
    features: ['Up to 250 active shipments', '20 team users', 'Multi-carrier REST APIs & Webhooks', 'Automated OCR bill parsing', 'QuickBooks integration'],
    is_active: true,
  },
  {
    id: 3,
    name: 'Enterprise Forwarder',
    code: 'ENTERPRISE_MONTHLY',
    monthly_price: 1299,
    annual_price: 12990,
    currency: 'USD',
    features: ['Unlimited shipments', 'Unlimited users', 'Full ocean carrier suite & EDI 214', 'Autonomous AI reasoning agents', 'Dedicated cloud document vault', '24/7 SLA'],
    is_active: true,
  },
];

export const MOCK_SUBSCRIPTIONS = [
  {
    id: 1,
    org_id: 1,
    org_name: 'Freel Global Logistics Pvt Ltd',
    plan_name: 'Enterprise Forwarder',
    plan_code: 'ENTERPRISE_MONTHLY',
    status: 'Active',
    amount: 1299,
    billing_cycle: 'Monthly',
    auto_renew: true,
    current_period_start: '2026-10-15T00:00:00Z',
    current_period_end: '2026-11-15T00:00:00Z',
    mrr: 1299,
    seats_used: 42,
    seats_limit: 100,
  },
  {
    id: 2,
    org_id: 2,
    org_name: 'LogisticsHQ Dev Org - Varun Logistics',
    plan_name: 'Enterprise Forwarder',
    plan_code: 'ENTERPRISE_MONTHLY',
    status: 'Active',
    amount: 999,
    billing_cycle: 'Monthly',
    auto_renew: true,
    current_period_start: '2026-10-20T00:00:00Z',
    current_period_end: '2026-11-20T00:00:00Z',
    mrr: 999,
    seats_used: 28,
    seats_limit: 50,
  },
  {
    id: 3,
    org_id: 3,
    org_name: 'OceanBridge Shipping Solutions',
    plan_name: 'Professional Suite',
    plan_code: 'PROFESSIONAL_MONTHLY',
    status: 'Active',
    amount: 599,
    billing_cycle: 'Monthly',
    auto_renew: true,
    current_period_start: '2026-10-05T00:00:00Z',
    current_period_end: '2026-12-05T00:00:00Z',
    mrr: 599,
    seats_used: 18,
    seats_limit: 20,
  },
  {
    id: 4,
    org_id: 4,
    org_name: 'Eastern Freight Lines',
    plan_name: 'Enterprise Forwarder',
    plan_code: 'ENTERPRISE_MONTHLY',
    status: 'Active',
    amount: 1299,
    billing_cycle: 'Monthly',
    auto_renew: false,
    current_period_start: '2026-09-12T00:00:00Z',
    current_period_end: '2026-12-12T00:00:00Z',
    mrr: 1299,
    seats_used: 45,
    seats_limit: 50,
  },
  {
    id: 5,
    org_id: 5,
    org_name: 'SkyLink Forwarders India',
    plan_name: 'Starter Forwarder',
    plan_code: 'STARTER_MONTHLY',
    status: 'Active',
    amount: 199,
    billing_cycle: 'Monthly',
    auto_renew: true,
    current_period_start: '2026-09-20T00:00:00Z',
    current_period_end: '2026-12-20T00:00:00Z',
    mrr: 199,
    seats_used: 12,
    seats_limit: 15,
  },
];

export const MOCK_SUPPORT_CASES = [
  {
    id: 401,
    case_number: 'SUP-2026-1042',
    org_id: 1,
    org_name: 'Freel Global Logistics Pvt Ltd',
    subject: 'Request for secondary Hapag-Lloyd API key rotation',
    status: 'RESOLVED',
    severity: 'MEDIUM',
    category: 'INTEGRATIONS',
    created_by: 'Varun Kanade',
    assigned_to: 'Support Engineering',
    created_at: '2026-10-07T08:30:00Z',
    resolved_at: '2026-10-07T11:15:00Z',
    notes: [
      { id: 1, author: 'Support Engineering', text: 'Verified tenant credentials and rotated credentials with zero downtime.', created_at: '2026-10-07T11:15:00Z' },
    ],
  },
  {
    id: 402,
    case_number: 'SUP-2026-1055',
    org_id: 1,
    org_name: 'Freel Global Logistics Pvt Ltd',
    subject: 'Customs declaration shipping bill OCR format clarification',
    status: 'IN_PROGRESS',
    severity: 'LOW',
    category: 'DOCUMENTS',
    created_by: 'Priya Sharma',
    assigned_to: 'AI Document Specialist',
    created_at: '2026-10-08T14:00:00Z',
    resolved_at: null,
    notes: [
      { id: 2, author: 'AI Document Specialist', text: 'Analyzing updated ICEGATE shipping bill format for neural table extractor.', created_at: '2026-10-08T15:00:00Z' },
    ],
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    title: 'Maersk Webhook Milestone Ingress',
    message: 'Container MSKU9182736 gated in at Nhava Sheva Terminal 4.',
    severity: 'INFO',
    category: 'SHIPMENT',
    is_read: false,
    created_at: '2026-10-09T05:12:30Z',
  },
  {
    id: 2,
    title: 'Customs Clearance Notice',
    message: 'HLCU7162534 cleared customs at Hamburg Port CTA.',
    severity: 'SUCCESS',
    category: 'CUSTOMS',
    is_read: false,
    created_at: '2026-10-09T03:55:00Z',
  },
  {
    id: 3,
    title: 'Document OCR Verification Complete',
    message: 'House Bill of Lading HBL_Shipment_101.pdf parsed with 99.4% confidence score.',
    severity: 'SUCCESS',
    category: 'DOCUMENTS',
    is_read: true,
    created_at: '2026-10-05T09:32:00Z',
  },
];

export const MOCK_ACTIVITY_TIMELINE = [
  { id: 1, category: 'CARRIER', action: 'EDI 214 Milestone Ingest', details: 'Maersk Line: MSKU9182736 Gate-In recorded at Nhava Sheva', actor_name: 'Maersk Webhook Engine', created_at: '2026-10-09T05:12:30Z' },
  { id: 2, category: 'DOCUMENTS', action: 'Document OCR Verified', details: 'HBL_Shipment_101.pdf extracted with 99.4% neural accuracy', actor_name: 'AWS Textract Engine', created_at: '2026-10-05T09:32:00Z' },
  { id: 3, category: 'BILLING', action: 'Invoice Auto-Reconciled', details: 'INV-2026-DEV-001 ($14,850.00 USD) settled via QuickBooks', actor_name: 'QuickBooks Sync Worker', created_at: '2026-09-30T10:00:00Z' },
  { id: 4, category: 'SECURITY', action: 'Integration Key Validated', details: 'Hapag-Lloyd Direct Gateway connection test successful (120ms)', actor_name: 'Varun Kanade', created_at: '2026-09-28T14:20:00Z' },
];

export const MOCK_AUDIT_LOGS = [
  { id: 1, module: 'INTEGRATIONS', action: 'TEST_CONNECTION', actor: 'Varun Kanade (CEO)', result: 'SUCCESS', details: 'Verified TLS 1.3 handshake with Hapag-Lloyd API', timestamp: '2026-10-09T05:15:00Z' },
  { id: 2, module: 'INTEGRATIONS', action: 'TOGGLE_CARRIER', actor: 'Varun Kanade (CEO)', result: 'SUCCESS', details: 'Enabled Maersk Line live webhook ingress', timestamp: '2026-10-09T04:30:00Z' },
  { id: 3, module: 'SUBSCRIPTIONS', action: 'AUTO_RENEW_TOGGLE', actor: 'Varun Kanade (CEO)', result: 'SUCCESS', details: 'Confirmed auto-renewal for Freel Global Logistics Enterprise plan', timestamp: '2026-10-08T11:00:00Z' },
  { id: 4, module: 'DOCUMENTS', action: 'STATUS_UPDATE', actor: 'Priya Sharma', result: 'SUCCESS', details: 'Verified Certificate of Origin Certificate_of_Origin_INNSA.pdf', timestamp: '2026-10-02T16:22:00Z' },
];

/**
 * Returns full Customer 360 foundation payload for an organization ID
 */
export function getMockOrganizationDetails(orgId) {
  const numId = Number(orgId) || 1;
  const org = MOCK_ORGANIZATIONS.find((o) => o.id === numId) || MOCK_ORGANIZATIONS[0];
  const sub = MOCK_SUBSCRIPTIONS.find((s) => s.org_id === numId) || MOCK_SUBSCRIPTIONS[0];

  return {
    organization: org,
    subscription: {
      plan_name: org.plan_name,
      plan_code: `${org.plan_name.toUpperCase()}_MONTHLY`,
      status: org.status === 'Active' ? 'Active' : org.status,
      billing_cycle: 'Monthly',
      current_period_end: org.renewal_date ? `${org.renewal_date}T00:00:00Z` : '2026-11-15T00:00:00Z',
      amount: sub?.amount || 1299,
      auto_renew: true,
    },
    users: MOCK_USERS,
    stats: {
      active_shipments_count: 14,
      outstanding_invoices_count: 6,
      open_exceptions_count: 2,
      expiring_contracts_count: 1,
      monthly_volume_usd: 142000,
      containers_in_transit: 28,
    },
    recent_activity: MOCK_ACTIVITY_TIMELINE,
    health: {
      status: org.health_status === 'Healthy' ? 'Healthy' : 'Needs Attention',
      score: org.health_status === 'Healthy' ? 88 : 72,
      summary: 'High operational engagement, healthy carrier API telemetries, and 0 critical churn signals.',
      risk_indicators: [],
    },
    shipment_trends: [
      { month: 'May 2026', shipments: 24, volume_teu: 48 },
      { month: 'Jun 2026', shipments: 29, volume_teu: 58 },
      { month: 'Jul 2026', shipments: 34, volume_teu: 68 },
      { month: 'Aug 2026', shipments: 41, volume_teu: 82 },
      { month: 'Sep 2026', shipments: 46, volume_teu: 92 },
      { month: 'Oct 2026', shipments: 52, volume_teu: 104 },
    ],
    open_alerts: [
      { id: 1, severity: 'WARNING', title: 'Belgian Customs Hold on Container HLCU7162534', message: 'HS code certificate review requested by Antwerp CTA terminal.', created_at: '2026-10-08T14:20:00Z' },
      { id: 2, severity: 'INFO', title: 'Carrier Service Contract Renewal Upcoming', message: 'MSC Volume Agreement SC-MSCU-88410-2026 expires in 27 days.', created_at: '2026-10-09T00:00:00Z' },
    ],
    team_summary: {
      total_users: MOCK_USERS.length,
      active_users: MOCK_USERS.filter((u) => u.status === 'ACTIVE').length,
      primary_admin: MOCK_USERS[0],
      other_key_users: MOCK_USERS.slice(1),
    },
  };
}

/**
 * Returns full Customer Integrations Overview for an organization ID
 */
export function getMockCustomerIntegrations(orgId) {
  const numId = Number(orgId) || 1;
  const org = MOCK_ORGANIZATIONS.find((o) => o.id === numId) || MOCK_ORGANIZATIONS[0];

  return {
    org_id: numId,
    org_name: org.name,
    total_configured: MOCK_INTEGRATION_ITEMS.length,
    active_connected: MOCK_INTEGRATION_ITEMS.filter((i) => i.status === 'CONNECTED').length,
    degraded_count: MOCK_INTEGRATION_ITEMS.filter((i) => i.status === 'CONFIGURATION_REQUIRED' || i.status === 'DEGRADED').length,
    error_count: MOCK_INTEGRATION_ITEMS.filter((i) => i.status === 'ERROR' || i.status === 'FAILED').length,
    overall_health_score: 94,
    overall_health_status: 'HEALTHY',
    items: MOCK_INTEGRATION_ITEMS,
    webhooks_summary: {
      total_received_30d: 8940,
      active_ingress_endpoints: 4,
      avg_processing_latency_ms: 45,
    },
    recent_webhooks: MOCK_WEBHOOKS,
    recent_sync_jobs: MOCK_SYNC_JOBS,
    available_providers: MOCK_CARRIER_CATALOG,
    carrier_catalog: MOCK_CARRIER_CATALOG,
    evaluated_at: new Date().toISOString(),
  };
}
