// Code generated by MockGen. DO NOT EDIT.
// Source: internal/users/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/users/repository.go -destination=internal/users/mock_repository.go -package=users
//

// Package users is a generated GoMock package.
package users

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddUserToOrg mocks base method.
func (m *MockRepository) AddUserToOrg(ctx context.Context, member *OrgMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToOrg", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToOrg indicates an expected call of AddUserToOrg.
func (mr *MockRepositoryMockRecorder) AddUserToOrg(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToOrg", reflect.TypeOf((*MockRepository)(nil).AddUserToOrg), ctx, member)
}

// CountActiveSuperAdmins mocks base method.
func (m *MockRepository) CountActiveSuperAdmins(ctx context.Context, orgID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveSuperAdmins", ctx, orgID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveSuperAdmins indicates an expected call of CountActiveSuperAdmins.
func (mr *MockRepositoryMockRecorder) CountActiveSuperAdmins(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveSuperAdmins", reflect.TypeOf((*MockRepository)(nil).CountActiveSuperAdmins), ctx, orgID)
}

// CreateInvitation mocks base method.
func (m *MockRepository) CreateInvitation(ctx context.Context, inv *Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockRepositoryMockRecorder) CreateInvitation(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockRepository)(nil).CreateInvitation), ctx, inv)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, user *User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, user)
}

// DeleteInvitation mocks base method.
func (m *MockRepository) DeleteInvitation(ctx context.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvitation", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvitation indicates an expected call of DeleteInvitation.
func (mr *MockRepositoryMockRecorder) DeleteInvitation(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvitation", reflect.TypeOf((*MockRepository)(nil).DeleteInvitation), ctx, orgID, id)
}

// GetInvitationByToken mocks base method.
func (m *MockRepository) GetInvitationByToken(ctx context.Context, token string) (*Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvitationByToken", ctx, token)
	ret0, _ := ret[0].(*Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvitationByToken indicates an expected call of GetInvitationByToken.
func (mr *MockRepositoryMockRecorder) GetInvitationByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvitationByToken", reflect.TypeOf((*MockRepository)(nil).GetInvitationByToken), ctx, token)
}

// GetMemberRoleName mocks base method.
func (m *MockRepository) GetMemberRoleName(ctx context.Context, orgID, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRoleName", ctx, orgID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRoleName indicates an expected call of GetMemberRoleName.
func (mr *MockRepositoryMockRecorder) GetMemberRoleName(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRoleName", reflect.TypeOf((*MockRepository)(nil).GetMemberRoleName), ctx, orgID, userID)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// ListInvitations mocks base method.
func (m *MockRepository) ListInvitations(ctx context.Context, orgID int64) ([]InvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx, orgID)
	ret0, _ := ret[0].([]InvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockRepositoryMockRecorder) ListInvitations(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockRepository)(nil).ListInvitations), ctx, orgID)
}

// ListOrgMembers mocks base method.
func (m *MockRepository) ListOrgMembers(ctx context.Context, orgID int64) ([]OrgMemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgMembers", ctx, orgID)
	ret0, _ := ret[0].([]OrgMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgMembers indicates an expected call of ListOrgMembers.
func (mr *MockRepositoryMockRecorder) ListOrgMembers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgMembers", reflect.TypeOf((*MockRepository)(nil).ListOrgMembers), ctx, orgID)
}

// RemoveMember mocks base method.
func (m *MockRepository) RemoveMember(ctx context.Context, orgID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockRepositoryMockRecorder) RemoveMember(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockRepository)(nil).RemoveMember), ctx, orgID, userID)
}

// UpdateMemberRole mocks base method.
func (m *MockRepository) UpdateMemberRole(ctx context.Context, orgID, userID, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, orgID, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockRepositoryMockRecorder) UpdateMemberRole(ctx, orgID, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockRepository)(nil).UpdateMemberRole), ctx, orgID, userID, roleID)
}
