"""
LogisticsHQ Phase 6.1 — Multi-Agent Workforce Foundation Models

Structured contracts for:
- Agent Registry & Metadata
- Capabilities
- Multi-Agent Tasks
- Inter-Agent Messages
- Controlled Shared Context
- Delegation & Handoffs
- Agent Results & Proposed Actions
"""

from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


class AgentType(str, Enum):
    COORDINATOR = "COORDINATOR"
    SPECIALIST = "SPECIALIST"
    EVALUATOR = "EVALUATOR"
    ANALYST = "ANALYST"


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ESCALATED = "ESCALATED"


class TaskPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class MessageType(str, Enum):
    REQUEST = "REQUEST"
    DELEGATION = "DELEGATION"
    CONTEXT = "CONTEXT"
    RESULT = "RESULT"
    STATUS = "STATUS"
    ESCALATION = "ESCALATION"
    ERROR = "ERROR"
    HANDOFF = "HANDOFF"


class ContextItemType(str, Enum):
    FACT = "FACT"
    PREDICTION = "PREDICTION"
    RECOMMENDATION = "RECOMMENDATION"
    AGENT_RESULT = "AGENT_RESULT"
    HUMAN_DECISION = "HUMAN_DECISION"
    SYSTEM_EVENT = "SYSTEM_EVENT"


class AutonomyLevel(str, Enum):
    LEVEL_0_OBSERVE = "LEVEL_0_OBSERVE"
    LEVEL_1_RECOMMEND = "LEVEL_1_RECOMMEND"
    LEVEL_2_PREPARE = "LEVEL_2_PREPARE"
    LEVEL_3_CONTROLLED_EXECUTION = "LEVEL_3_CONTROLLED_EXECUTION"
    LEVEL_4_GOVERNED_MULTI_STEP = "LEVEL_4_GOVERNED_MULTI_STEP"


class AgentCapability(BaseModel):
    key: str
    name: str
    description: str
    required_autonomy_level: str = AutonomyLevel.LEVEL_1_RECOMMEND.value


class AgentMetadata(BaseModel):
    agent_id: str
    agent_type: AgentType
    name: str
    description: str
    capabilities: List[str]
    allowed_tasks: List[str]
    allowed_entities: List[str]
    autonomy_level: str = "LEVEL_1_RECOMMEND"
    is_enabled: bool = True
    version: str = "1.0.0"
    prompt_version: str = "1.0.0"
    health_status: str = "HEALTHY"


class ContextReference(BaseModel):
    context_id: str
    item_type: ContextItemType
    entity_type: Optional[str] = None
    entity_id: Optional[str] = None
    source_agent_id: Optional[str] = None
    provenance_id: Optional[str] = None
    content: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = 1.0
    is_authoritative: bool = False


class ProposedAction(BaseModel):
    """
    Action proposal generated by Python AI.
    CRITICAL: Python does NOT execute this! It is returned to Go,
    which validates and routes it through the authoritative Go Action System.
    """
    action_type: str
    entity_type: str = "SYSTEM"
    entity_id: str = "N/A"
    target_entity: Optional[str] = None
    target_id: Optional[str] = None
    parameters: Dict[str, Any] = Field(default_factory=dict)
    payload: Dict[str, Any] = Field(default_factory=dict)
    risk_level: str = "LOW"
    confidence: float = 1.0
    requires_approval: bool = True
    reasoning: str = ""


class DelegationRequest(BaseModel):
    target_agent_id: str
    objective: str
    required_capabilities: List[str]
    context_references: List[str] = Field(default_factory=list)
    expected_output: str
    priority: TaskPriority = TaskPriority.MEDIUM


class HandoffContract(BaseModel):
    originating_task_id: str
    source_agent_id: str
    destination_agent_id: str
    reason: str
    objective: str
    required_capability: str
    context_references: List[str] = Field(default_factory=list)
    current_findings: Dict[str, Any] = Field(default_factory=dict)
    expected_output: str
    confidence: float = 0.0


class WorkforceMessageContract(BaseModel):
    message_id: str
    task_id: str
    parent_task_id: Optional[str] = None
    sender_agent_id: str
    recipient_agent_id: str
    message_type: MessageType
    objective: str
    requested_capability: Optional[str] = None
    context_reference: Optional[Dict[str, Any]] = None
    payload: Dict[str, Any] = Field(default_factory=dict)
    priority: TaskPriority = TaskPriority.MEDIUM
    correlation_id: str
    created_at: Optional[str] = None


class WorkforceTaskContract(BaseModel):
    task_id: str
    org_id: int
    objective: str
    initiating_event: Optional[str] = None
    parent_task_id: Optional[str] = None
    root_task_id: Optional[str] = None
    assigned_agent_id: str
    status: TaskStatus = TaskStatus.PENDING
    priority: TaskPriority = TaskPriority.MEDIUM
    context_references: Optional[List[ContextReference]] = Field(default_factory=list)
    required_capabilities: Optional[List[str]] = Field(default_factory=list)
    dependencies: Optional[List[str]] = Field(default_factory=list)
    correlation_id: str


class RecoveryOption(BaseModel):
    """
    Structured recovery option generated during exception and disruption handling.
    CRITICAL: Returned as a proposal — Go Action System governs execution!
    """
    option_id: str  # e.g. "OPTION_A", "OPTION_B", "OPTION_C", "OPTION_D"
    title: str
    description: str
    expected_benefit: str
    operational_impact: str
    customer_impact: str
    financial_impact: str
    risks: str
    confidence: float = 0.85
    required_capabilities: List[str] = Field(default_factory=list)
    requires_approval: bool = False


class CrossModuleRisk(BaseModel):
    """
    Structured Cross-Module Risk representation (Phase 6.7).
    Consolidates operational, contractual, compliance, financial, and commercial exposures.
    """
    risk_id: str
    tenant_id: Optional[int] = None
    originating_task_id: str = ""
    risk_type: str = "cross_module"  # operational, shipment, exception, customer, pricing, financial, contract, compliance, documentation, commercial, cross_module
    severity: str = "medium"  # low, medium, high, critical
    probability: float = 0.5
    impact: str = ""
    affected_modules: List[str] = Field(default_factory=list)
    affected_entities: Dict[str, Any] = Field(default_factory=dict)
    contributing_agents: List[str] = Field(default_factory=list)
    evidence_references: List[str] = Field(default_factory=list)
    facts: List[Dict[str, Any]] = Field(default_factory=list)
    predictions: List[Dict[str, Any]] = Field(default_factory=list)
    recommendations: List[Dict[str, Any]] = Field(default_factory=list)
    confidence: float = 0.85
    uncertainty: List[str] = Field(default_factory=list)
    missing_data: List[str] = Field(default_factory=list)
    status: str = "IDENTIFIED"  # IDENTIFIED, UNDER_REVIEW, ESCALATED, RESOLVED, SUPERSEDED
    escalation_requirement: bool = False
    approval_requirement: bool = False
    parent_risk_id: Optional[str] = None
    version: int = 1
    superseded_risk_id: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class AgentExecutionResult(BaseModel):
    task_id: str
    agent_id: str
    status: TaskStatus
    confidence: float = 0.0
    objective: str = ""
    findings: Dict[str, Any] = Field(default_factory=dict)
    summary: str = ""
    facts: List[Dict[str, Any]] = Field(default_factory=list)
    known_facts: List[Dict[str, Any]] = Field(default_factory=list)
    likely_causes: List[Dict[str, Any]] = Field(default_factory=list)
    predictions: List[Dict[str, Any]] = Field(default_factory=list)
    recommendations: List[Dict[str, Any]] = Field(default_factory=list)
    recovery_options: List[RecoveryOption] = Field(default_factory=list)
    quotation_recommendation: Optional[Dict[str, Any]] = None
    cross_module_risk: Optional[CrossModuleRisk] = None
    risk_assessments: List[CrossModuleRisk] = Field(default_factory=list)
    missing_data: List[str] = Field(default_factory=list)
    evidence: List[str] = Field(default_factory=list)
    requested_follow_up_agents: List[str] = Field(default_factory=list)
    escalation_indicator: bool = False
    proposed_delegations: List[DelegationRequest] = Field(default_factory=list)
    proposed_handoff: Optional[HandoffContract] = None
    proposed_actions: List[ProposedAction] = Field(default_factory=list)
    new_context_items: List[Dict[str, Any]] = Field(default_factory=list)
    decision_record: Optional[Dict[str, Any]] = None
    collaborative_plan: Optional[Dict[str, Any]] = None
    messages: List[WorkforceMessageContract] = Field(default_factory=list)
    error_code: Optional[str] = None
    error_message: Optional[str] = None
    created_at: Optional[str] = None


class SpecialistContribution(BaseModel):
    agent_id: str
    task_id: str
    confidence: float = 0.0
    facts: List[Dict[str, Any]] = Field(default_factory=list)
    predictions: List[Dict[str, Any]] = Field(default_factory=list)
    recommendations: List[Dict[str, Any]] = Field(default_factory=list)
    evidence: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)
    escalation_indicator: bool = False
    timestamp: Optional[str] = None


class ConflictRecord(BaseModel):
    conflict_id: str
    tenant_id: Optional[int] = None
    task_id: Optional[str] = None
    parent_task_id: Optional[str] = None
    topic: str
    agent_a: str
    recommendation_a: Dict[str, Any] = Field(default_factory=dict)
    agent_b: str
    recommendation_b: Dict[str, Any] = Field(default_factory=dict)
    participating_agents: List[str] = Field(default_factory=list)
    conflicting_results: Optional[Dict[str, Any]] = None
    conflict_type: str = "recommendation"  # factual, prediction, recommendation, priority, business_constraint, incomplete_information, policy
    evidence: List[str] = Field(default_factory=list)
    confidence_values: Dict[str, float] = Field(default_factory=dict)
    business_constraints: List[str] = Field(default_factory=list)
    reasoning: str = ""
    severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CRITICAL
    resolution_status: str = "DETECTED"  # DETECTED, RESOLVED, UNRESOLVED, ESCALATED_TO_HUMAN
    resolution_strategy: str = "ESCALATE_TO_HUMAN"  # CONSENSUS, AUTHORITATIVE_DATA_OVERRIDE, DATA_FRESHNESS_PREFERENCE, BUSINESS_RULE_PRIORITY, MEMORY_EVIDENCE_WEIGHTED, ESCALATE_TO_HUMAN
    is_resolved: bool = False
    resolved_recommendation: Optional[Dict[str, Any]] = None
    selected_outcome: Optional[Dict[str, Any]] = None
    unresolved_reason: Optional[str] = None
    escalation_requirement: bool = False
    created_at: Optional[str] = None
    resolved_at: Optional[str] = None


class AgentOutcome(BaseModel):
    outcome_id: str
    tenant_id: Optional[int] = None
    source_task_id: Optional[str] = None
    source_agent_id: Optional[str] = None
    source_entity_type: str = "SHIPMENT"
    source_entity_id: str
    objective: str = ""
    recommendation: Optional[Dict[str, Any]] = None
    action_type: Optional[str] = None
    human_decision: Optional[str] = None  # NONE, APPROVED, MODIFIED, OVERRIDDEN, HALTED, ESCALATED
    human_feedback: Optional[str] = None
    actual_outcome: str = ""
    status: str = "UNVERIFIED"  # SUCCESS, PARTIAL_SUCCESS, FAILED, CANCELLED, REJECTED, SUPERSEDED, ESCALATED, UNVERIFIED
    is_verified: bool = False
    success_indicator: bool = True
    evidence: List[str] = Field(default_factory=list)
    lesson: Optional[str] = None
    confidence: float = 1.0
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: Optional[str] = None


class DecisionRecord(BaseModel):
    decision_id: str
    objective: str
    participating_agents: List[str] = Field(default_factory=list)
    specialist_contributions: List[SpecialistContribution] = Field(default_factory=list)
    conflicts: List[ConflictRecord] = Field(default_factory=list)
    selected_recommendation: Optional[Dict[str, Any]] = None
    quotation_recommendation: Optional[Dict[str, Any]] = None
    cross_module_risk: Optional[CrossModuleRisk] = None
    risk_assessments: List[CrossModuleRisk] = Field(default_factory=list)
    outcomes: List[AgentOutcome] = Field(default_factory=list)
    memory_insights: List[Dict[str, Any]] = Field(default_factory=list)
    missing_data: List[str] = Field(default_factory=list)
    consensus_summary: str = ""
    overall_confidence: float = 0.0
    confidence_rationale: str = ""
    uncertainty_indicators: List[str] = Field(default_factory=list)
    assumptions: List[str] = Field(default_factory=list)
    requires_human_approval: bool = False
    approval_reason: Optional[str] = None
    proposed_actions: List[ProposedAction] = Field(default_factory=list)
    recovery_options: List[RecoveryOption] = Field(default_factory=list)
    correlation_id: str = ""
    created_at: Optional[str] = None


class CollaborativePlanStep(BaseModel):
    step_id: str
    agent_id: str
    objective: str
    dependencies: List[str] = Field(default_factory=list)
    required_capabilities: List[str] = Field(default_factory=list)
    expected_output: str = ""
    is_required: bool = True
    status: str = "PENDING"
    task_id: Optional[str] = None
    result: Optional[Dict[str, Any]] = None
    confidence: float = 0.0
    error_message: Optional[str] = None


class CollaborativePlan(BaseModel):
    plan_id: str
    planning_task_id: str
    objective: str
    coordinator_agent_id: str = "planning_agent"
    participating_agents: List[str] = Field(default_factory=list)
    steps: List[CollaborativePlanStep] = Field(default_factory=list)
    completed_steps: List[str] = Field(default_factory=list)
    failed_steps: List[str] = Field(default_factory=list)
    status: str = "CREATED"
    final_decision: Optional[DecisionRecord] = None
    cross_module_risk: Optional[CrossModuleRisk] = None
    risk_assessments: List[CrossModuleRisk] = Field(default_factory=list)
    conflicts: List[ConflictRecord] = Field(default_factory=list)
    outcomes: List[AgentOutcome] = Field(default_factory=list)
    memory_insights: List[Dict[str, Any]] = Field(default_factory=list)
    overall_confidence: float = 0.0
    escalation_state: bool = False
    requires_approval: bool = False
    version: int = 1
    superseded_plan_id: Optional[str] = None
    trigger_event: Optional[str] = None
    recovery_options: List[RecoveryOption] = Field(default_factory=list)
    created_at: Optional[str] = None


