CREATE TABLE IF NOT EXISTS rfq_documents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    rfq_id BIGINT NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'MISSING',
    file_name VARCHAR(500) NULL,
    file_url VARCHAR(1000) NULL,
    file_size BIGINT NULL,
    mime_type VARCHAR(100) NULL,
    uploaded_by VARCHAR(255) NULL,
    uploaded_at DATETIME NULL,
    reviewed_by VARCHAR(255) NULL,
    reviewed_at DATETIME NULL,
    rejection_reason TEXT NULL,
    expires_at DATETIME NULL,
    metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rfq_docs_rfq (org_id, rfq_id),
    INDEX idx_rfq_docs_status (status)
);
