-- 061_spot_rate_requests_and_responses.sql
-- Task 19.4: Carrier Rate Management, Spot Rate Requests & Rate Comparison Intelligence

CREATE TABLE IF NOT EXISTS spot_rate_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    request_reference VARCHAR(64) NOT NULL,
    customer_id BIGINT NULL,
    customer_name VARCHAR(255) NULL,
    origin_port VARCHAR(128) NOT NULL,
    origin_code VARCHAR(32) NULL,
    destination_port VARCHAR(128) NOT NULL,
    destination_code VARCHAR(32) NULL,
    transport_mode VARCHAR(64) NOT NULL DEFAULT 'Ocean FCL',
    service_type VARCHAR(64) NOT NULL DEFAULT 'FCL',
    equipment_type VARCHAR(64) NULL DEFAULT '40GP',
    commodity VARCHAR(255) NULL,
    cargo_weight DECIMAL(12, 2) NULL,
    cargo_volume DECIMAL(12, 2) NULL,
    container_quantity INT NOT NULL DEFAULT 1,
    ready_date DATE NOT NULL,
    target_currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    required_by_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    notes TEXT NULL,
    created_by VARCHAR(128) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_srr_org_status (org_id, status),
    INDEX idx_srr_org_ref (org_id, request_reference),
    INDEX idx_srr_org_lane (org_id, origin_port, destination_port),
    INDEX idx_srr_org_created (org_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS spot_rate_responses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    spot_rate_request_id BIGINT NOT NULL,
    carrier_name VARCHAR(255) NOT NULL,
    carrier_code VARCHAR(32) NULL,
    supplier_name VARCHAR(255) NULL,
    rate_id BIGINT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    base_amount DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
    transit_days INT NULL,
    free_days_origin INT NOT NULL DEFAULT 0,
    free_days_destination INT NOT NULL DEFAULT 0,
    valid_from DATE NOT NULL,
    valid_until DATE NOT NULL,
    routing_notes TEXT NULL,
    response_notes TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    is_preferred BOOLEAN NOT NULL DEFAULT FALSE,
    responded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(128) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sresp_org_req (org_id, spot_rate_request_id),
    INDEX idx_sresp_org_carrier (org_id, carrier_name),
    INDEX idx_sresp_org_pref (org_id, is_preferred),
    INDEX idx_sresp_org_valid (org_id, valid_until),
    CONSTRAINT fk_sresp_request FOREIGN KEY (spot_rate_request_id) REFERENCES spot_rate_requests (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS spot_rate_response_charges (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    spot_rate_response_id BIGINT NOT NULL,
    charge_category VARCHAR(64) NOT NULL DEFAULT 'FREIGHT',
    charge_name VARCHAR(128) NOT NULL,
    calculation_basis VARCHAR(32) NOT NULL DEFAULT 'FLAT',
    quantity DECIMAL(12, 2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    display_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_srrc_org_resp (org_id, spot_rate_response_id),
    CONSTRAINT fk_srrc_response FOREIGN KEY (spot_rate_response_id) REFERENCES spot_rate_responses (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
