-- Migration 089: AI Action and Recommendation Center
-- Stores grounded, deterministic-first AI recommendations with verified evidence,
-- tenant isolation, status transitions, assignment, dismissal tracking, and approval linkage.

CREATE TABLE IF NOT EXISTS ai_recommendations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    source_type VARCHAR(64) NOT NULL COMMENT 'CUSTOMER, SHIPMENT, INVOICE, RFQ, QUOTATION, CONTRACT, LEAD',
    source_id BIGINT NOT NULL,
    source_reference VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(64) NOT NULL COMMENT 'customer, sales, rfq, pricing, quotation, shipment, operations, exception, invoice, finance, contract, compliance, collections, general',
    priority VARCHAR(32) NOT NULL DEFAULT 'medium' COMMENT 'low, medium, high, critical',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'medium' COMMENT 'low, medium, high, critical',
    confidence VARCHAR(32) NOT NULL DEFAULT 'HIGH' COMMENT 'HIGH, MEDIUM, LOW',
    confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0.85,
    evidence JSON NOT NULL COMMENT 'Array of structured evidence items',
    recommended_action TEXT NOT NULL,
    action_type VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'new' COMMENT 'new, reviewed, assigned, approved, rejected, dismissed, completed, failed',
    assignee_id BIGINT NULL,
    assignee_name VARCHAR(128) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at DATETIME NULL,
    reviewed_by_id BIGINT NULL,
    completed_at DATETIME NULL,
    completed_by_id BIGINT NULL,
    dismissed_at DATETIME NULL,
    dismissed_by_id BIGINT NULL,
    dismissed_reason TEXT NULL,
    freshness DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NULL,
    requires_approval TINYINT(1) NOT NULL DEFAULT 0,
    approval_id BIGINT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    created_by VARCHAR(128) NOT NULL DEFAULT 'SYSTEM',
    generated_by VARCHAR(128) NOT NULL DEFAULT 'DETERMINISTIC_RULES',
    rule_applied VARCHAR(128) NOT NULL,
    dedup_hash VARCHAR(64) NOT NULL,
    metadata JSON NULL,
    INDEX idx_ai_rec_org_status (org_id, status),
    INDEX idx_ai_rec_org_category (org_id, category),
    INDEX idx_ai_rec_org_priority (org_id, priority),
    INDEX idx_ai_rec_org_source (org_id, source_type, source_id),
    INDEX idx_ai_rec_org_dedup (org_id, dedup_hash),
    INDEX idx_ai_rec_org_created (org_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
