-- Migration 096: Centralized Notification and Escalation Center
-- Stores real in-app notifications, delivery state, read state, dismissals, and auditable escalation events.

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    user_id BIGINT NULL COMMENT 'Specific recipient user ID; NULL if broadcast to organization/role',
    role_target VARCHAR(50) NULL COMMENT 'Target role e.g. SUPER_ADMIN, OPERATIONS, FINANCE, SALES; NULL = all permitted',
    source_module VARCHAR(50) NOT NULL COMMENT 'SHIPMENTS, INVOICES, CONTRACTS, APPROVALS, AUTOMATIONS, RECOMMENDATIONS, SYSTEM',
    source_record_type VARCHAR(50) NOT NULL COMMENT 'SHIPMENT, INVOICE, CONTRACT, DOCUMENT, APPROVAL, AUTOMATION, RECOMMENDATION',
    source_record_id VARCHAR(100) NOT NULL COMMENT 'Unique identifier of the source record',
    recommendation_id BIGINT NULL,
    approval_id BIGINT NULL,
    automation_execution_id BIGINT NULL,
    notification_type VARCHAR(100) NOT NULL COMMENT 'HIGH_PRIORITY_RECOMMENDATION, ASSIGNED_RECOMMENDATION, CRITICAL_SHIPMENT_EXCEPTION, MISSED_SHIPMENT_MILESTONE, OVERDUE_INVOICE_RISK, EXPIRING_CONTRACT, PENDING_APPROVAL, REJECTED_APPROVAL, AUTOMATION_RUN_FAILED, COMPLIANCE_REVIEW_REQUIRED, SYSTEM_ALERT',
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    severity VARCHAR(30) NOT NULL DEFAULT 'INFORMATIONAL' COMMENT 'INFORMATIONAL, LOW, MEDIUM, HIGH, CRITICAL',
    priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW, MEDIUM, HIGH, URGENT',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE, RESOLVED, DISMISSED, EXPIRED',
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    read_at DATETIME NULL,
    is_dismissed TINYINT(1) NOT NULL DEFAULT 0,
    dismissed_at DATETIME NULL,
    is_escalated TINYINT(1) NOT NULL DEFAULT 0,
    escalation_level INT NOT NULL DEFAULT 0,
    escalated_at DATETIME NULL,
    action_required TINYINT(1) NOT NULL DEFAULT 0,
    action_url VARCHAR(255) NULL,
    dedup_hash VARCHAR(64) NOT NULL COMMENT 'SHA256 hash of org, source record, and active issue type',
    correlation_id VARCHAR(255) NOT NULL,
    expires_at DATETIME NULL,
    metadata LONGTEXT NULL COMMENT 'JSON payload with extra context',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_notif_org_read (org_id, is_read, is_dismissed, created_at DESC),
    INDEX idx_notif_user_read (user_id, is_read, is_dismissed),
    INDEX idx_notif_module (org_id, source_module, created_at DESC),
    INDEX idx_notif_severity (org_id, severity, is_read),
    INDEX idx_notif_escalated (org_id, is_escalated),
    UNIQUE INDEX idx_notif_dedup (org_id, dedup_hash),
    INDEX idx_notif_rec (org_id, recommendation_id),
    INDEX idx_notif_appr (org_id, approval_id),
    INDEX idx_notif_exec (org_id, automation_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_escalation_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    escalation_level INT NOT NULL DEFAULT 1,
    escalation_reason VARCHAR(255) NOT NULL,
    previous_severity VARCHAR(30) NOT NULL,
    new_severity VARCHAR(30) NOT NULL,
    trigger_type VARCHAR(50) NOT NULL DEFAULT 'TIME_THRESHOLD' COMMENT 'TIME_THRESHOLD, REPEATED_FAILURE, MANUAL',
    threshold_hours INT NOT NULL DEFAULT 0,
    acknowledged_at DATETIME NULL,
    acknowledged_by BIGINT NULL,
    resolved_at DATETIME NULL,
    resolved_by BIGINT NULL,
    correlation_id VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_esc_notif (notification_id),
    INDEX idx_esc_org (org_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_notification_preferences (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    min_severity VARCHAR(32) NOT NULL DEFAULT 'INFORMATIONAL' COMMENT 'INFORMATIONAL, LOW, MEDIUM, HIGH, CRITICAL',
    in_app_enabled TINYINT(1) NOT NULL DEFAULT 1,
    assigned_only TINYINT(1) NOT NULL DEFAULT 0,
    approvals_enabled TINYINT(1) NOT NULL DEFAULT 1,
    automations_enabled TINYINT(1) NOT NULL DEFAULT 1,
    recommendations_enabled TINYINT(1) NOT NULL DEFAULT 1,
    finance_enabled TINYINT(1) NOT NULL DEFAULT 1,
    operations_enabled TINYINT(1) NOT NULL DEFAULT 1,
    compliance_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX idx_user_notif_pref (org_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
