-- Migration 100: Phase 3 Task 3.2 Controlled AI Workflow Execution and Action Orchestration
-- Establishes durable storage for AI action proposals, execution lifecycle, and post-execution verification.

CREATE TABLE IF NOT EXISTS ai_action_proposals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    proposal_id VARCHAR(128) NOT NULL UNIQUE,
    source_module VARCHAR(64) NOT NULL,
    source_record_type VARCHAR(64) NOT NULL,
    source_record_id VARCHAR(128) NOT NULL,
    trigger_event VARCHAR(128) NOT NULL,
    proposed_action_type VARCHAR(128) NOT NULL,
    action_parameters JSON NOT NULL,
    explanation TEXT NOT NULL,
    evidence JSON NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL DEFAULT 0.0000,
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW',
    priority VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    approval_policy VARCHAR(64) NOT NULL DEFAULT 'ALWAYS_REQUIRE_APPROVAL',
    expected_impact TEXT NOT NULL,
    reversibility VARCHAR(64) NOT NULL DEFAULT 'REVERSIBLE',
    missing_information JSON NULL,
    data_freshness VARCHAR(64) NOT NULL DEFAULT 'REAL_TIME',
    correlation_id VARCHAR(128) NOT NULL,
    approval_id BIGINT NULL,
    execution_id BIGINT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'PROPOSED',
    schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
    created_by BIGINT NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_prop_org_status (org_id, status),
    INDEX idx_ai_prop_org_source (org_id, source_module, source_record_id),
    INDEX idx_ai_prop_correlation (correlation_id),
    INDEX idx_ai_prop_approval (approval_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_action_executions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    proposal_id VARCHAR(128) NOT NULL,
    action_name VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL UNIQUE,
    status VARCHAR(64) NOT NULL DEFAULT 'QUEUED',
    current_step VARCHAR(64) NOT NULL DEFAULT 'QUEUED',
    step_results JSON NULL,
    input_payload JSON NOT NULL,
    output_payload JSON NULL,
    verification_status VARCHAR(64) NOT NULL DEFAULT 'NOT_VERIFIED',
    verification_details JSON NULL,
    retry_count INT NOT NULL DEFAULT 0,
    max_retries INT NOT NULL DEFAULT 3,
    error_message TEXT NULL,
    executed_by BIGINT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ai_exec_org_status (org_id, status),
    INDEX idx_ai_exec_org_action (org_id, action_name),
    INDEX idx_ai_exec_correlation (correlation_id),
    INDEX idx_ai_exec_proposal (proposal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
