-- Migration 105: Phase 3 Task 3.8 - Event-Driven AI Workflows and Cross-Module Automation
-- Stores ingested system domain events with deduplication and tracks execution of cross-module AI workflows.

CREATE TABLE IF NOT EXISTS ai_event_store (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    source_module VARCHAR(64) NOT NULL,
    source_record_type VARCHAR(64) NOT NULL,
    source_record_id VARCHAR(64) NOT NULL,
    event_version VARCHAR(16) NOT NULL DEFAULT '1.0',
    actor_type VARCHAR(32) NOT NULL DEFAULT 'SYSTEM',
    actor_id BIGINT NULL,
    payload JSON NOT NULL,
    dedup_key VARCHAR(191) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    failure_reason TEXT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    correlation_id VARCHAR(128) NOT NULL,
    causation_id VARCHAR(128) NULL,
    event_timestamp DATETIME NOT NULL,
    processed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_aes_org_event (org_id, event_type),
    INDEX idx_aes_dedup (org_id, dedup_key),
    INDEX idx_aes_source (org_id, source_record_type, source_record_id),
    INDEX idx_aes_created (org_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_cross_module_workflows (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    workflow_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    trigger_event_type VARCHAR(64) NOT NULL,
    source_module VARCHAR(64) NOT NULL,
    source_record_type VARCHAR(64) NOT NULL,
    source_record_id VARCHAR(64) NOT NULL,
    urgency VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
    ai_summary TEXT NOT NULL,
    ai_analysis JSON NOT NULL,
    recommendations JSON NOT NULL,
    action_intent JSON NULL,
    approval_id BIGINT NULL,
    action_name VARCHAR(64) NULL,
    action_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    draft_id BIGINT NULL,
    dedup_key VARCHAR(191) NOT NULL,
    correlation_id VARCHAR(128) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_acmw_org_status (org_id, status),
    INDEX idx_acmw_org_type (org_id, workflow_type),
    INDEX idx_acmw_dedup (org_id, dedup_key),
    INDEX idx_acmw_event (org_id, event_id),
    INDEX idx_acmw_created (org_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
