-- Migration 123: Phase 6 Task 6.1 Multi-Agent Workforce Foundation
-- Establishes durable persistence for agent registry, multi-agent task lifecycle,
-- structured inter-agent messages, controlled shared context, and agent handoffs.

CREATE TABLE IF NOT EXISTS workforce_agents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL DEFAULT 0 COMMENT '0 for system baseline default, or specific tenant org_id',
    agent_id VARCHAR(100) NOT NULL COMMENT 'Canonical agent identifier, e.g. planning_agent, shipment_agent',
    agent_type VARCHAR(50) NOT NULL DEFAULT 'SPECIALIST' COMMENT 'COORDINATOR, SPECIALIST, EVALUATOR, ANALYST',
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    capabilities JSON NOT NULL COMMENT 'Array of string capability keys, e.g. ["shipment.read", "shipment.analyze"]',
    allowed_tasks JSON NOT NULL COMMENT 'Array of allowed task type strings',
    allowed_entities JSON NOT NULL COMMENT 'Array of allowed entity types: SHIPMENT, INVOICE, CUSTOMER, etc.',
    autonomy_level VARCHAR(50) NOT NULL DEFAULT 'LEVEL_1_RECOMMEND',
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    version VARCHAR(50) NOT NULL DEFAULT '1.0.0',
    prompt_version VARCHAR(50) NOT NULL DEFAULT '1.0.0',
    health_status VARCHAR(50) NOT NULL DEFAULT 'HEALTHY' COMMENT 'HEALTHY, DEGRADED, OFFLINE',
    last_execution_at DATETIME NULL,
    last_execution_info JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_workforce_agent_org (org_id, agent_id),
    INDEX idx_workforce_agents_type (org_id, agent_type, is_enabled),
    INDEX idx_workforce_agents_health (org_id, health_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workforce_tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL UNIQUE,
    org_id BIGINT NOT NULL,
    objective TEXT NOT NULL,
    initiating_event VARCHAR(100) NULL,
    parent_task_id VARCHAR(100) NULL COMMENT 'Parent task ID if this is a delegated child task',
    root_task_id VARCHAR(100) NULL COMMENT 'Root task ID of the delegation tree',
    assigned_agent_id VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, ASSIGNED, RUNNING, WAITING, BLOCKED, COMPLETED, FAILED, CANCELLED, ESCALATED',
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW, MEDIUM, HIGH, URGENT',
    context_reference JSON NULL COMMENT 'Structured references to entity, memory, or external artifacts',
    required_capabilities JSON NOT NULL COMMENT 'Array of capabilities required to execute this task',
    dependencies JSON NULL COMMENT 'Array of prerequisite task IDs that must complete first',
    result JSON NULL COMMENT 'Structured validated outcome returned by agent',
    confidence DECIMAL(5, 4) NOT NULL DEFAULT 0.0000,
    error_code VARCHAR(100) NULL,
    error_message TEXT NULL,
    correlation_id VARCHAR(100) NOT NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_wf_tasks_org_status (org_id, status),
    INDEX idx_wf_tasks_parent (org_id, parent_task_id),
    INDEX idx_wf_tasks_root (org_id, root_task_id),
    INDEX idx_wf_tasks_agent (org_id, assigned_agent_id),
    INDEX idx_wf_tasks_corr (org_id, correlation_id),
    INDEX idx_wf_tasks_created (org_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workforce_messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(100) NOT NULL UNIQUE,
    org_id BIGINT NOT NULL,
    task_id VARCHAR(100) NOT NULL,
    parent_task_id VARCHAR(100) NULL,
    sender_agent_id VARCHAR(100) NOT NULL,
    recipient_agent_id VARCHAR(100) NOT NULL,
    message_type VARCHAR(50) NOT NULL COMMENT 'REQUEST, DELEGATION, CONTEXT, RESULT, STATUS, ESCALATION, ERROR, HANDOFF',
    objective TEXT NOT NULL,
    requested_capability VARCHAR(100) NULL,
    context_reference JSON NULL,
    payload JSON NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    correlation_id VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_wf_msgs_task (org_id, task_id),
    INDEX idx_wf_msgs_sender_recip (org_id, sender_agent_id, recipient_agent_id),
    INDEX idx_wf_msgs_type (org_id, message_type),
    INDEX idx_wf_msgs_corr (org_id, correlation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workforce_contexts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    context_id VARCHAR(100) NOT NULL UNIQUE,
    org_id BIGINT NOT NULL,
    task_id VARCHAR(100) NOT NULL,
    item_type VARCHAR(50) NOT NULL COMMENT 'FACT, PREDICTION, RECOMMENDATION, AGENT_RESULT, HUMAN_DECISION, SYSTEM_EVENT',
    entity_type VARCHAR(50) NULL COMMENT 'SHIPMENT, INVOICE, CUSTOMER, RFQ, CONTRACT, RATE',
    entity_id VARCHAR(100) NULL,
    source_agent_id VARCHAR(100) NULL,
    provenance_id VARCHAR(100) NULL,
    content JSON NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL DEFAULT 1.0000,
    is_authoritative TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_wf_ctx_task (org_id, task_id),
    INDEX idx_wf_ctx_item_type (org_id, item_type),
    INDEX idx_wf_ctx_entity (org_id, entity_type, entity_id),
    INDEX idx_wf_ctx_auth (org_id, is_authoritative)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS workforce_handoffs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    handoff_id VARCHAR(100) NOT NULL UNIQUE,
    org_id BIGINT NOT NULL,
    task_id VARCHAR(100) NOT NULL,
    originating_task_id VARCHAR(100) NOT NULL,
    source_agent_id VARCHAR(100) NOT NULL,
    destination_agent_id VARCHAR(100) NOT NULL,
    reason TEXT NOT NULL,
    objective TEXT NOT NULL,
    required_capability VARCHAR(100) NOT NULL,
    context_references JSON NULL,
    current_findings JSON NULL,
    expected_output TEXT NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL DEFAULT 0.0000,
    status VARCHAR(40) NOT NULL DEFAULT 'INITIATED' COMMENT 'INITIATED, ACCEPTED, REJECTED, COMPLETED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_wf_handoff_task (org_id, task_id),
    INDEX idx_wf_handoff_agents (org_id, source_agent_id, destination_agent_id),
    INDEX idx_wf_handoff_status (org_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
