export const COUNTRIES = [
  { code: '+1', iso: 'US', label: 'United States' },
  { code: '+1', iso: 'CA', label: 'Canada' },
  { code: '+44', iso: 'GB', label: 'United Kingdom' },
  { code: '+91', iso: 'IN', label: 'India' },
  { code: '+61', iso: 'AU', label: 'Australia' },
  { code: '+971', iso: 'AE', label: 'United Arab Emirates' },
  { code: '+65', iso: 'SG', label: 'Singapore' },
  { code: '+49', iso: 'DE', label: 'Germany' },
  { code: '+33', iso: 'FR', label: 'France' },
  { code: '+81', iso: 'JP', label: 'Japan' },
  { code: '+86', iso: 'CN', label: 'China' },
  { code: '+55', iso: 'BR', label: 'Brazil' },
  { code: '+52', iso: 'MX', label: 'Mexico' },
  { code: '+27', iso: 'ZA', label: 'South Africa' },
  { code: '+234', iso: 'NG', label: 'Nigeria' },
  { code: '+254', iso: 'KE', label: 'Kenya' },
  { code: '+20', iso: 'EG', label: 'Egypt' },
  { code: '+966', iso: 'SA', label: 'Saudi Arabia' },
  { code: '+62', iso: 'ID', label: 'Indonesia' },
  { code: '+60', iso: 'MY', label: 'Malaysia' },
  { code: '+63', iso: 'PH', label: 'Philippines' },
  { code: '+64', iso: 'NZ', label: 'New Zealand' },
  { code: '+82', iso: 'KR', label: 'South Korea' },
  { code: '+34', iso: 'ES', label: 'Spain' },
  { code: '+39', iso: 'IT', label: 'Italy' },
  { code: '+31', iso: 'NL', label: 'Netherlands' },
  { code: '+32', iso: 'BE', label: 'Belgium' },
  { code: '+41', iso: 'CH', label: 'Switzerland' },
  { code: '+46', iso: 'SE', label: 'Sweden' },
  { code: '+47', iso: 'NO', label: 'Norway' },
  { code: '+45', iso: 'DK', label: 'Denmark' },
  { code: '+358', iso: 'FI', label: 'Finland' },
  { code: '+48', iso: 'PL', label: 'Poland' },
  { code: '+43', iso: 'AT', label: 'Austria' },
  { code: '+353', iso: 'IE', label: 'Ireland' },
  { code: '+92', iso: 'PK', label: 'Pakistan' },
  { code: '+880', iso: 'BD', label: 'Bangladesh' },
  { code: '+94', iso: 'LK', label: 'Sri Lanka' },
  { code: '+977', iso: 'NP', label: 'Nepal' },
  { code: '+54', iso: 'AR', label: 'Argentina' },
  { code: '+56', iso: 'CL', label: 'Chile' },
  { code: '+57', iso: 'CO', label: 'Colombia' },
  { code: '+51', iso: 'PE', label: 'Peru' },
  { code: '+58', iso: 'VE', label: 'Venezuela' },
  { code: '+90', iso: 'TR', label: 'Turkey' },
  { code: '+98', iso: 'IR', label: 'Iran' },
  { code: '+964', iso: 'IQ', label: 'Iraq' },
  { code: '+972', iso: 'IL', label: 'Israel' },
  { code: '+962', iso: 'JO', label: 'Jordan' },
  { code: '+961', iso: 'LB', label: 'Lebanon' },
  { code: '+965', iso: 'KW', label: 'Kuwait' },
  { code: '+974', iso: 'QA', label: 'Qatar' },
  { code: '+973', iso: 'BH', label: 'Bahrain' },
  { code: '+968', iso: 'OM', label: 'Oman' },
  { code: '+84', iso: 'VN', label: 'Vietnam' },
  { code: '+66', iso: 'TH', label: 'Thailand' },
  { code: '+95', iso: 'MM', label: 'Myanmar' },
  { code: '+855', iso: 'KH', label: 'Cambodia' },
  { code: '+856', iso: 'LA', label: 'Laos' },
  { code: '+673', iso: 'BN', label: 'Brunei' },
  { code: '+886', iso: 'TW', label: 'Taiwan' },
  { code: '+852', iso: 'HK', label: 'Hong Kong' },
  { code: '+853', iso: 'MO', label: 'Macau' },
  { code: '+351', iso: 'PT', label: 'Portugal' },
  { code: '+30', iso: 'GR', label: 'Greece' },
  { code: '+420', iso: 'CZ', label: 'Czech Republic' },
  { code: '+36', iso: 'HU', label: 'Hungary' },
  { code: '+40', iso: 'RO', label: 'Romania' },
  { code: '+359', iso: 'BG', label: 'Bulgaria' },
  { code: '+381', iso: 'RS', label: 'Serbia' },
  { code: '+385', iso: 'HR', label: 'Croatia' },
  { code: '+386', iso: 'SI', label: 'Slovenia' },
  { code: '+421', iso: 'SK', label: 'Slovakia' },
  { code: '+372', iso: 'EE', label: 'Estonia' },
  { code: '+371', iso: 'LV', label: 'Latvia' },
  { code: '+370', iso: 'LT', label: 'Lithuania' },
  { code: '+380', iso: 'UA', label: 'Ukraine' },
  { code: '+375', iso: 'BY', label: 'Belarus' },
  { code: '+7', iso: 'RU', label: 'Russia' },
  { code: '+7', iso: 'KZ', label: 'Kazakhstan' },
  { code: '+998', iso: 'UZ', label: 'Uzbekistan' },
  { code: '+212', iso: 'MA', label: 'Morocco' },
  { code: '+213', iso: 'DZ', label: 'Algeria' },
  { code: '+216', iso: 'TN', label: 'Tunisia' },
  { code: '+251', iso: 'ET', label: 'Ethiopia' },
  { code: '+255', iso: 'TZ', label: 'Tanzania' },
  { code: '+256', iso: 'UG', label: 'Uganda' },
  { code: '+233', iso: 'GH', label: 'Ghana' },
  { code: '+225', iso: 'CI', label: 'Ivory Coast' },
  { code: '+221', iso: 'SN', label: 'Senegal' },
  { code: '+237', iso: 'CM', label: 'Cameroon' },
  { code: '+244', iso: 'AO', label: 'Angola' },
  { code: '+260', iso: 'ZM', label: 'Zambia' },
  { code: '+263', iso: 'ZW', label: 'Zimbabwe' },
  { code: '+258', iso: 'MZ', label: 'Mozambique' },
  { code: '+261', iso: 'MG', label: 'Madagascar' },
  { code: '+230', iso: 'MU', label: 'Mauritius' }
];

// Helper to convert ISO code to an emoji flag
export function getFlagEmoji(isoCode) {
  if (!isoCode) return '🌐';
  const codePoints = isoCode
    .toUpperCase()
    .split('')
    .map(char => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
